import{describe,expect,it,vi}from"vitest";vi.mock("server-only",()=>({}));import{addedProductsHtml,addedProductsPdf,addedProductsPdfFilename}from"./pdf";import type{AddedProductsLabels}from"@/components/added-products-note";import{createTranslator}from"@/lib/i18n/core";import{addedProductsLabels}from"./labels";
const document={document_number:"GR-20260919-000001",created_at:"2026-09-19T09:00:00Z",created_by_name:"admin",location_names:["Warehouse"],product_count:1,total_weight:2,total_value:400};
const longBarcode="12345678901234567890";
const items=[{line_number:1,category_name:"Каблучка",article_number:"A1",producer:"Виробник",size:"17",weight_grams:2,price_per_gram:200,price:400,location_name:"Warehouse",barcode:longBarcode}];
const labels:AddedProductsLabels={title:"Накладна надходження товару",number:"№ документа",date:"Дата створення",locations:"Локації",products:"Вироби",totalWeight:"Вага",totalValue:"Вартість",createdBy:"Створив",signature:"Прийняв",headings:Array.from({length:10},(_,i)=>String(i)),location:(x:string)=>x};
describe("Added Products PDF",()=>{
 it.each(["en","ua"] as const)("uses localized numeric-only boundary prices and concise %s headers",async locale=>{const localized=addedProductsLabels(createTranslator(locale),locale),html=await addedProductsHtml(document,[{...items[0],price_per_gram:24390,price:295607}],localized,locale),normalized=html.replace(/[\u00a0\u202f]/g," "),priceCells=[...normalized.matchAll(/<td class="transfer-note__cell--price(?:-per-gram)?">([^<]+)<\/td>/g)].map(match=>match[1]);if(locale==="en")expect(normalized).toContain('transfer-note__heading-main\">Price per Gram</span><span class="transfer-note__heading-unit\">(UAH)');else{expect(normalized).toContain('transfer-note__heading-main\">Ціна/г, грн</span>');expect(normalized).toContain('transfer-note__heading-main\">Ціна, грн</span>')}expect(priceCells).toEqual(locale==="en"?["24,390.00","295,607.00"]:["24 390,00","295 607,00"]);expect(priceCells.join(" ")).not.toMatch(/UAH|грн/)});
 it("locks the Ukrainian receipt profile to realistic maximum field envelopes",async()=>{const boundary={...items[0],category_name:"Перстень діаманти (0,05ct)",article_number:"shmfpD600040|R55",producer:"Золотий Соверен",size:"17,5-18,5",weight_grams:12.12,price_per_gram:24390,price:295607,location_name:"Novovolynsk",barcode:longBarcode},html=await addedProductsHtml({...document,product_count:3},[boundary,items[0],{...items[0],line_number:3,location_name:"Kamin"}],addedProductsLabels(createTranslator("ua"),"ua"),"ua"),normalized=html.replace(/[\u00a0\u202f]/g," ");for(const value of[boundary.category_name,boundary.article_number,boundary.producer,boundary.size,"Нововолинськ",longBarcode,"24 390,00","295 607,00"])expect(normalized).toContain(value);for(const rule of['article class="transfer-note added-products-note transfer-note--ua-table"',"added-products-note.transfer-note--ua-table .transfer-note__col--article{width:15.5%}","added-products-note.transfer-note--ua-table .transfer-note__col--price-per-gram{width:9.5%}","added-products-note.transfer-note--ua-table .transfer-note__col--price{width:10.5%}","added-products-note.transfer-note--ua-table .transfer-note__col--location{width:12%}","added-products-note.transfer-note--ua-table .transfer-note__col--barcode{width:13%}"])expect(html).toContain(rule);expect(html).not.toContain("text-overflow:ellipsis");expect(html).not.toContain("word-break:break-all");for(const confidential of["Purchase Price","Purchase Value","IN_STOCK","2026-09-19T09:00:00Z"])expect(html).not.toContain(confidential)});
 it.skipIf(process.env.CI)("creates a valid PDF with Cyrillic content in local Chromium",async()=>{const pdf=await addedProductsPdf(document,items,labels,"ua");expect(Buffer.from(pdf.subarray(0,5)).toString()).toBe("%PDF-");expect(pdf.byteLength).toBeGreaterThan(10_000)});
 it("uses the immutable document number in the filename",()=>expect(addedProductsPdfFilename(document.document_number)).toBe("goods-receipt-GR-20260919-000001.pdf"));
});
