import{describe,expect,it,vi}from"vitest";vi.mock("server-only",()=>({}));import{addedProductsHtml,addedProductsPdf,addedProductsPdfFilename}from"./pdf";import type{AddedProductsLabels}from"@/components/added-products-note";import{createTranslator}from"@/lib/i18n/core";import{addedProductsLabels}from"./labels";
const document={document_number:"GR-20260919-000001",created_at:"2026-09-19T09:00:00Z",created_by_name:"admin",location_names:["Warehouse"],product_count:1,total_weight:2,total_value:400};
const longBarcode="012345678901234567890123456789";
const items=[{line_number:1,category_name:"Каблучка",article_number:"A1",producer:"Виробник",size:"17",weight_grams:2,price_per_gram:200,price:400,location_name:"Warehouse",barcode:longBarcode}];
const labels:AddedProductsLabels={title:"Накладна надходження товару",number:"№ документа",date:"Дата створення",locations:"Локації",products:"Вироби",totalWeight:"Вага",totalValue:"Вартість",createdBy:"Створив",signature:"Прийняв",headings:Array.from({length:10},(_,i)=>String(i)),location:(x:string)=>x};
describe("Added Products PDF",()=>{
 it.each(["en","ua"] as const)("uses localized numeric-only price cells and currency-bearing %s headers",async locale=>{const localized=addedProductsLabels(createTranslator(locale),locale),html=await addedProductsHtml(document,[{...items[0],price_per_gram:1200,price:6000}],localized,locale),normalized=html.replace(/[\u00a0\u202f]/g," "),priceCells=[...normalized.matchAll(/<td class="transfer-note__cell--price(?:-per-gram)?">([^<]+)<\/td>/g)].map(match=>match[1]);expect(normalized).toContain(locale==="en"?"Price per Gram (UAH)":"Ціна за грам (грн)");expect(priceCells).toEqual(locale==="en"?["1,200.00","6,000.00"]:["1 200,00","6 000,00"]);expect(priceCells.join(" ")).not.toMatch(/UAH|грн/)});
 it("uses semantic columns and preserves representative long values",async()=>{const longItems=[{...items[0],category_name:"Надзвичайно довга категорія ювелірних виробів",article_number:"ARTICLE-WITH-A-LONG-IDENTIFIER-2026",producer:"Виробник із дуже довгою офіційною назвою",price_per_gram:1234567.89,price:9876543.21,location_name:"Warehouse with extended location name",barcode:longBarcode},items[0]],html=await addedProductsHtml({...document,product_count:2},longItems,addedProductsLabels(createTranslator("ua"),"ua"),"ua");for(const value of[longItems[0].category_name,longItems[0].article_number,longItems[0].producer,longBarcode])expect(html).toContain(value);expect(html).toContain("transfer-note__col--price-per-gram");expect(html).toContain("transfer-note__cell--barcode");expect(html).toContain("overflow-wrap:anywhere");expect(html).toContain("white-space:nowrap");expect(html).not.toContain("text-overflow:ellipsis");for(const confidential of["Purchase Price","Purchase Value","IN_STOCK","2026-09-19T09:00:00Z"])expect(html).not.toContain(confidential)});
 it.skipIf(process.env.CI)("creates a valid PDF with Cyrillic content in local Chromium",async()=>{const pdf=await addedProductsPdf(document,items,labels,"ua");expect(Buffer.from(pdf.subarray(0,5)).toString()).toBe("%PDF-");expect(pdf.byteLength).toBeGreaterThan(10_000)});
 it("uses the immutable document number in the filename",()=>expect(addedProductsPdfFilename(document.document_number)).toBe("goods-receipt-GR-20260919-000001.pdf"));
});
