import Link from "next/link";
import {getAddedProductDocuments} from "@/lib/added-products/queries";
import {formatPrice} from "@/lib/inventory/format";
import {getTranslations} from "@/lib/i18n/server";
import {historicalLocationDisplayName} from "@/lib/locations/display";
import {getTransfers} from "@/lib/transfers/queries";
import {PageHeading} from "@/components/ui/page-heading";
import {buttonStyles} from "@/components/ui/button";

const actionClass="font-medium text-amber-900 underline underline-offset-4";
export default async function DocumentsPage({searchParams}:{searchParams:Promise<{type?:string}>}){
 const type=(await searchParams).type==="added"?"added":"transfers",[{t,locale},rows]=await Promise.all([getTranslations(),type==="added"?getAddedProductDocuments():getTransfers()]),date=(value:string)=>new Intl.DateTimeFormat(locale==="ua"?"uk-UA":"en-US",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Kyiv"}).format(new Date(value));
 return <section><PageHeading title={t("documents.title")} /><nav className="mt-5 flex gap-2" aria-label={t("documents.types")}><Link className={buttonStyles(type==="transfers"?"primary":"secondary")} href="/documents?type=transfers">{t("transfers.title")}</Link><Link className={buttonStyles(type==="added"?"primary":"secondary")} href="/documents?type=added">{t("addedProducts.title")}</Link></nav><div className="zl-table-wrap mt-4">
 {type==="transfers"?<table className="zl-table min-w-[900px]"><thead><tr>{[t("transfers.number"),t("fields.createdDate"),t("transfers.from"),t("transfers.to"),t("transfers.items"),t("transfers.totalWeight"),t("transfers.totalValue"),t("documents.actions")].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{(rows as Awaited<ReturnType<typeof getTransfers>>).map(x=><tr key={x.id}><td>{x.transfer_number}</td><td className="whitespace-nowrap">{date(x.transferred_at)}</td><td>{historicalLocationDisplayName(x.source_name,locale)}</td><td>{historicalLocationDisplayName(x.destination_name,locale)}</td><td>{x.item_count}</td><td className="whitespace-nowrap">{x.total_weight} g</td><td className="whitespace-nowrap text-right">{formatPrice(x.total_value,locale)}</td><td className="whitespace-nowrap"><span className="flex gap-3"><Link className={actionClass} href={`/transfers/${x.id}`}>{t("documents.view")}</Link><a className={actionClass} href={`/api/transfers/${x.id}/pdf`} download>{t("transfers.downloadPdf")}</a></span></td></tr>)}</tbody></table>
 :<table className="zl-table min-w-[820px]"><thead><tr>{[t("documents.documentNumber"),t("fields.createdDate"),t("addedProducts.products"),t("addedProducts.totalWeight"),t("addedProducts.totalValue"),t("documents.createdBy"),t("documents.actions")].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{(rows as Awaited<ReturnType<typeof getAddedProductDocuments>>).map(x=><tr key={x.id}><td>{x.document_number}</td><td className="whitespace-nowrap">{date(x.created_at)}</td><td>{x.product_count}</td><td className="whitespace-nowrap">{x.total_weight} g</td><td className="whitespace-nowrap text-right">{formatPrice(x.total_value,locale)}</td><td>{x.created_by_name}</td><td className="whitespace-nowrap"><span className="flex gap-3"><Link className={actionClass} href={`/documents/added-products/${x.id}`}>{t("documents.view")}</Link><a className={actionClass} href={`/api/added-products/${x.id}/pdf`} download>{t("addedProducts.downloadPdf")}</a></span></td></tr>)}</tbody></table>}
 </div></section>;
}
