import Link from "next/link";
import { SalesTrend } from "@/components/sales-trend";
import { getCurrentEmployee, getInventoryOptions } from "@/lib/inventory/queries";
import { formatDateTime, formatPrice } from "@/lib/inventory/format";
import { getDashboardReport } from "@/lib/dashboard/queries";
import { dashboardSections, PERIOD_LABELS, REPORTING_PERIODS, reportingPeriod } from "@/lib/dashboard/model";

export const metadata = { title: "Dashboard" };
type SearchParams = Promise<Record<string, string | string[] | undefined>>;
const textParam = (value: string | string[] | undefined) => typeof value === "string" ? value : "";
const grams = (value: number) => `${new Intl.NumberFormat("en", { maximumFractionDigits: 3 }).format(value)} g`;
function Metric({ label, value, note }: { label: string; value: string; note?: string }) { return <div className="rounded-xl border border-stone-200 bg-white p-5 shadow-sm"><p className="text-xs font-medium uppercase tracking-wide text-stone-500">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p>{note ? <p className="mt-1 text-xs text-stone-500">{note}</p> : null}</div>; }

export default async function DashboardPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const employee = await getCurrentEmployee();
  const requestedPeriod = reportingPeriod(textParam(params.period));
  const requestedShop = textParam(params.shop) || null;
  const period = requestedPeriod;
  const shopId = employee.role === "owner" ? requestedShop : employee.shop_id;
  const [report, options] = await Promise.all([getDashboardReport(period, shopId), getInventoryOptions()]);
  const sections = dashboardSections(employee.role);

  return <section>
    <div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-medium uppercase tracking-widest text-stone-500">Business overview</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Dashboard</h1><p className="mt-2 text-sm text-stone-600">Reporting days use Europe/Kyiv time. Current period: {PERIOD_LABELS[report.period]}.</p></div>
      <form className="flex flex-wrap items-end gap-3 rounded-xl border border-stone-200 bg-white p-4 shadow-sm"><label className="text-sm font-medium">Period<select name="period" defaultValue={period} className="mt-1 block rounded-lg border border-stone-300 bg-white px-3 py-2">{REPORTING_PERIODS.map((value) => <option key={value} value={value}>{PERIOD_LABELS[value]}</option>)}</select></label>{employee.role === "owner" ? <label className="text-sm font-medium">Shop<select name="shop" defaultValue={shopId ?? ""} className="mt-1 block rounded-lg border border-stone-300 bg-white px-3 py-2"><option value="">All shops</option>{options.shops.map((shop) => <option key={shop.id} value={shop.id}>{shop.name}</option>)}</select></label> : <div className="text-sm font-medium">Shop<p className="mt-1 rounded-lg border bg-stone-50 px-3 py-2">{options.shops.find((shop)=>shop.id===employee.shop_id)?.name??"Assigned shop"}</p></div>}<button className="rounded-lg bg-stone-900 px-4 py-2 text-sm font-medium text-white">Apply</button></form>
    </div>
    <div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Revenue" value={formatPrice(report.kpis.revenue)} /><Metric label="Items sold" value={String(report.kpis.items_sold)} /><Metric label="Gold weight sold" value={grams(report.kpis.gold_weight_sold)} /></div>
    {sections.inventory && report.inventory && report.status_counts ? <><div className="mt-10"><h2 className="text-xl font-semibold">Current inventory</h2><p className="mt-1 text-sm text-stone-500">Valued dynamically at current effective customer prices; missing prices are excluded.</p></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="In-stock items" value={String(report.inventory.in_stock_items)} /><Metric label="In-stock gold weight" value={grams(report.inventory.in_stock_weight)} /><Metric label="Total value" value={formatPrice(report.inventory.customer_value)} note={`${report.inventory.missing_price_items} item(s) missing price`} /><div className="rounded-xl border border-stone-200 bg-white p-5 shadow-sm"><p className="text-xs font-medium uppercase tracking-wide text-stone-500">Status summary</p><div className="mt-3 grid grid-cols-2 gap-2 text-sm">{(["IN_STOCK","SOLD","REMOVED"] as const).map((status) => <div key={status}><span className="text-stone-500">{status.replace("_", " ")}</span><strong className="ml-2">{report.status_counts![status]}</strong></div>)}</div></div></div></> : null}
    {sections.comparisons && report.sales_over_time ? <div className="mt-10 rounded-xl border border-stone-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Sales over time</h2><p className="mt-1 text-sm text-stone-500">Daily revenue in Ukraine business time.</p><div className="mt-5"><SalesTrend points={report.sales_over_time} /></div></div> : null}
    {sections.comparisons ? <div className="mt-10 grid gap-6 xl:grid-cols-2"><ReportTable title="Sales by category" headings={["Category","Items","Revenue","Weight"]} empty="No category sales in this period." rows={(report.categories ?? []).map((row) => [row.category,String(row.items_sold),formatPrice(row.revenue),grams(row.weight_sold)])} /><ReportTable title="Employee sales" headings={["Employee","Shop","Sales","Items","Revenue","Average"]} empty="No employee sales in this period." rows={(report.employees ?? []).map((row) => [row.employee,row.shop,String(row.sales_count),String(row.items_sold),formatPrice(row.revenue),formatPrice(row.average_sale)])} /></div> : null}
    {sections.shopPerformance && report.shops ? <div className="mt-10"><ReportTable title="Shop performance" headings={["Shop","Revenue","Sales","Items","Sold weight","In stock","Stock weight","Inventory value"]} empty="No active shops." rows={report.shops.map((row) => [row.shop,formatPrice(row.revenue),String(row.sales_count),String(row.items_sold),grams(row.weight_sold),String(row.in_stock_items),grams(row.in_stock_weight),formatPrice(row.inventory_value)])} /></div> : null}
    <div className="mt-10"><h2 className="text-xl font-semibold">Recent sales</h2><div className="mt-4 overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm">{report.recent_sales.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-stone-200 bg-stone-50 text-xs uppercase text-stone-500"><tr>{["Sale","Date","Shop","Employee","Items","Total",""] .map((heading) => <th key={heading} className="px-4 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-stone-100">{report.recent_sales.map((sale) => <tr key={sale.id}><td className="px-4 py-3 font-semibold">{sale.sale_number}</td><td className="px-4 py-3 whitespace-nowrap">{formatDateTime(sale.sold_at)}</td><td className="px-4 py-3">{sale.shop}</td><td className="px-4 py-3">{sale.employee}</td><td className="px-4 py-3">{sale.item_count}</td><td className="px-4 py-3 whitespace-nowrap">{formatPrice(sale.total_sale_price)}</td><td className="px-4 py-3"><Link href={`/sales/${sale.id}`} className="font-medium text-amber-900 hover:underline">View</Link></td></tr>)}</tbody></table></div> : <p className="p-10 text-center text-sm text-stone-500">No completed sales yet.</p>}</div></div>
  </section>;
}

function ReportTable({ title, headings, rows, empty }: { title: string; headings: string[]; rows: string[][]; empty: string }) { return <div><h2 className="text-xl font-semibold">{title}</h2><div className="mt-4 overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm">{rows.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-stone-200 bg-stone-50 text-xs uppercase text-stone-500"><tr>{headings.map((heading) => <th key={heading} className="px-4 py-3 whitespace-nowrap">{heading}</th>)}</tr></thead><tbody className="divide-y divide-stone-100">{rows.map((row, index) => <tr key={`${row[0]}-${index}`}>{row.map((cell, cellIndex) => <td key={`${cellIndex}-${cell}`} className="px-4 py-3 whitespace-nowrap">{cell}</td>)}</tr>)}</tbody></table></div> : <p className="p-8 text-center text-sm text-stone-500">{empty}</p>}</div></div>; }
