import Link from "next/link";
import { getAdminData } from "@/lib/admin/queries";
import { deleteEmployeeAccount } from "@/lib/admin/actions";
import { ConfirmActionButton } from "@/components/confirm-action-button";

export const metadata = { title: "Account administration" };

export default async function EmployeesPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const [{ employees }, params] = await Promise.all([getAdminData(), searchParams]);
  return <section><Link href="/admin" className="text-sm text-stone-600">← Administration</Link><div className="mt-6 flex flex-col items-start gap-4 sm:flex-row sm:items-end sm:justify-between"><h1 className="text-3xl font-semibold">Accounts</h1><Link href="/admin/employees/invite" className="rounded-lg bg-stone-900 px-5 py-2.5 text-sm font-medium text-white">Create account</Link></div>{params.error ? <p role="alert" className="mt-5 rounded-lg bg-red-50 p-4 text-red-800">{params.error}</p> : null}<div className="mt-6 overflow-x-auto rounded-xl border bg-white" aria-label="Accounts">{employees.length ? <table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b bg-stone-50 text-xs uppercase text-stone-500"><tr>{["Username", "Role", "Shop", "Status", "Actions"].map(heading => <th key={heading} className="px-4 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y">{employees.map(employee => <tr key={employee.id}><td className="px-4 py-3 font-medium">{employee.username || employee.full_name || "Legacy account"}</td><td className="px-4 py-3 capitalize">{employee.role}</td><td className="px-4 py-3">{employee.shops?.name || "Unassigned"}</td><td className="px-4 py-3">{employee.is_active ? "Active" : "Inactive"}</td><td className="px-4 py-3"><div className="flex gap-3"><Link href={`/admin/employees/${employee.id}/edit`} className="font-medium text-amber-900 hover:underline">Edit</Link><ConfirmActionButton action={deleteEmployeeAccount.bind(null,employee.id)} label="Delete" title="Delete account permanently?" name={employee.username || employee.full_name || "Account"} message="This action cannot be undone." danger /></div></td></tr>)}</tbody></table> : <p className="p-10 text-center text-sm text-stone-500">No accounts.</p>}</div></section>;
}
