import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";const read=(path:string)=>readFileSync(new URL(path,import.meta.url),"utf8");
describe("Added Products documents",()=>{
 it("creates the receipt and snapshots in the atomic batch RPC",()=>{const sql=read("../../supabase/migrations/20260919180000_document_confidentiality_and_actor_username.sql");expect(sql).toContain("create or replace function public.create_inventory_items_batch");expect(sql).toContain("insert into public.added_product_documents");expect(sql).toContain("insert into public.added_product_document_items");expect(sql).toContain("return jsonb_build_object('count',v_row,'document_id',v_document_id)");expect(sql).not.toContain("commit;")});
 it("keeps immutable snapshots and Owner-only reads",()=>{const original=read("../../supabase/migrations/20260919120000_added_product_documents.sql");for(const field of["category_name","article_number","producer","size","weight_grams","purchase_price","price_per_gram","price","status","location_name","barcode","product_created_at"])expect(original).toContain(field);expect(original).toContain("using(public.is_owner())");expect(original).toContain("revoke all on public.added_product_documents")});
 it("clears drafts only after a confirmed document id",()=>{const basket=read("./inventory-draft-basket.tsx"),submit=basket.slice(basket.indexOf("function submit"));expect(submit).toContain("if(!result.error&&result.documentId)");expect(submit.indexOf("setDocumentId(result.documentId)")).toBeLessThan(submit.indexOf("clearManualDrafts(window.localStorage,ownerId)"));expect(basket).toContain("/api/added-products/${documentId}/pdf")});
 it("keeps both document histories in one switched workspace",()=>{const page=read("../app/(protected)/documents/page.tsx"),nav=read("./navigation.tsx"),legacy=read("../app/(protected)/transfers/page.tsx"),queries=read("../lib/added-products/queries.ts");expect(nav).toContain("/documents");expect(page).toMatch(/type\s*===\s*"added"/);expect(page).toContain("getTransfers");expect(page).toContain("getAddedProductDocuments");expect(queries).toContain('order("created_at",{ascending:false})');expect(legacy).toContain("/documents?type=transfers")});
 it("uses shared CSS and natural localized titles",()=>{const note=read("./added-products-note.tsx"),ua=read("../../locales/ua.json"),en=read("../../locales/en.json");expect(note).toContain("TRANSFER_NOTE_CSS");expect(note).toContain("Europe/Kyiv");expect(ua).toContain("Накладна надходження товару");expect(en).toContain('"noteTitle":"Goods Receipt"')});
 it("exposes only the final 10 receipt columns and three totals",()=>{const labels=read("../lib/added-products/labels.ts"),note=read("./added-products-note.tsx");expect(labels).toContain('t("fields.pricePerGram"),t("fields.priceUah"),t("fields.shop"),t("fields.barcode")');for(const forbidden of['t("fields.purchasePrice")','t("fields.status")'])expect(labels).not.toContain(forbidden);for(const confidential of["purchase_price","total_purchase_value","product_created_at","labels.status"])expect(note).not.toContain(confidential)});
 it("uses native download anchors",()=>{for(const file of["../app/(protected)/documents/page.tsx","../app/(protected)/documents/added-products/[id]/page.tsx","../app/(protected)/transfers/[id]/page.tsx","./inventory-draft-basket.tsx"]){const source=read(file);expect(source).toContain(" download");expect(source).not.toMatch(/<Link[^>]+href=\{?`?\/api\/(added-products|transfers)/)}});
});
