"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useRef, useState, useTransition } from "react";
import type { Tables } from "@/lib/database.types";
import { bulkMoveInventoryItems } from "@/lib/inventory/actions";
import { InventoryStatus } from "@/components/inventory-status";
import { displayValue, formatPrice } from "@/lib/inventory/format";
import { inventoryOrdinal } from "@/lib/inventory/pagination";

type Item=Tables<"inventory_items">&{product_categories:{name:string}|null;shops:{name:string;code:string|null}|null};
type Shop={id:string;name:string};
export function InventoryBulkTable({items,shops,page,pageSize,canManage}:{items:Item[];shops:Shop[];page:number;pageSize:number;canManage:boolean}){
  const router=useRouter();const[selected,setSelected]=useState<string[]>([]);const[destination,setDestination]=useState("");const[state,setState]=useState({error:"",success:""});const[pending,startTransition]=useTransition();const dialog=useRef<HTMLDialogElement>(null);
  const allSelected=items.length>0&&selected.length===items.length;
  function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);setState({error:"",success:""});}
  function confirm(){dialog.current?.close();startTransition(async()=>{const result=await bulkMoveInventoryItems(selected,destination||null);setState({error:result.error,success:result.success??""});if(!result.error){setSelected([]);router.refresh();}});}
  return <>
    {canManage?<div className="flex flex-wrap items-center gap-3 border-b border-stone-200 bg-stone-50 px-4 py-3"><button type="button" onClick={()=>setSelected(allSelected?[]:items.map(item=>item.id))} className="text-sm font-medium text-amber-900">{allSelected?"Clear selection":"Select all on current page"}</button>{selected.length?<><button type="button" onClick={()=>setSelected([])} className="text-sm text-stone-600">Clear selection</button><span className="text-sm font-medium">{selected.length} selected</span><label className="ml-auto text-sm font-medium">Bulk Actions: Move to Shop <select aria-label="Destination shop" value={destination} onChange={event=>setDestination(event.target.value)} className="ml-2 rounded-lg border border-stone-300 bg-white px-3 py-2"><option value="">Unassigned</option>{shops.map(shop=><option key={shop.id} value={shop.id}>{shop.name}</option>)}</select></label><button type="button" disabled={pending} onClick={()=>dialog.current?.showModal()} className="rounded-lg bg-stone-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{pending?"Moving…":"Move selected"}</button></>:null}</div>:null}
    {state.error?<p role="alert" className="m-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{state.error}</p>:null}{state.success?<p role="status" className="m-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{state.success}</p>:null}
    <div className="overflow-x-auto"><table className={`${canManage?"min-w-[1660px]":"min-w-[1600px]"} w-full text-left text-sm`}><thead className="border-b border-stone-200 bg-stone-50 text-xs uppercase tracking-wide text-stone-500"><tr>{canManage?<th className="px-4 py-3"><span className="sr-only">Select</span></th>:null}{["Nr","Product Category","Producer","Metal","Fineness","Size","Weight","Price per Gram","Article","Price (UAH)","Notes","Status","Shop","Barcode"].map(heading=><th key={heading} className="px-4 py-3 font-medium">{heading}</th>)}</tr></thead><tbody className="divide-y divide-stone-100">{items.map((item,index)=><tr key={item.id} className="hover:bg-amber-50/40">{canManage?<td className="px-4 py-3"><input type="checkbox" aria-label={`Select product ${item.barcode??item.article_number??inventoryOrdinal(page,pageSize,index)}`} checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/></td>:null}<td className="px-4 py-3 font-medium"><Link href={`/inventory/${item.id}`} className="text-amber-900 underline-offset-4 hover:underline">{inventoryOrdinal(page,pageSize,index)}</Link></td><td className="px-4 py-3">{item.product_categories?.name??"—"}</td><td className="px-4 py-3">{displayValue(item.producer)}</td><td className="px-4 py-3">{displayValue(item.metal)}</td><td className="px-4 py-3">{displayValue(item.gold_fineness)}</td><td className="px-4 py-3">{displayValue(item.size)}</td><td className="px-4 py-3">{item.weight_grams===null?"—":`${item.weight_grams} g`}</td><td className="px-4 py-3 whitespace-nowrap">{formatPrice(item.price_per_gram)}</td><td className="px-4 py-3">{displayValue(item.article_number)}</td><td className="px-4 py-3 whitespace-nowrap">{formatPrice(item.price)}</td><td className="max-w-80 px-4 py-3"><span className="line-clamp-2">{displayValue(item.notes)}</span></td><td className="px-4 py-3"><InventoryStatus status={item.status}/></td><td className="px-4 py-3">{item.shops?.name??"Unassigned"}</td><td className="px-4 py-3 font-medium">{displayValue(item.barcode)}</td></tr>)}</tbody></table></div>
    <dialog ref={dialog} className="m-auto w-[calc(100%-2rem)] max-w-md rounded-xl border bg-white p-6 shadow-2xl backdrop:bg-stone-950/50"><h2 className="text-xl font-semibold">Move selected products?</h2><p className="mt-3 text-sm text-stone-600">Move {selected.length} selected product{selected.length===1?"":"s"} to {shops.find(shop=>shop.id===destination)?.name??"Unassigned"}. The move is atomic and will be recorded in Product History.</p><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>dialog.current?.close()} className="px-4 py-2 text-sm">Cancel</button><button type="button" onClick={confirm} className="rounded-lg bg-stone-900 px-4 py-2 text-sm font-medium text-white">Confirm move</button></div></dialog>
  </>;
}
