"use client";
import {useEffect,useRef,useState,useTransition} from "react";
import {createInventoryBatch,type DraftProduct} from "@/lib/inventory/actions";
import {formatPrice} from "@/lib/inventory/format";
import {normalizeScannedBarcode} from "@/lib/inventory/scanner";
import {draftValidation,requiredDraftFields as required,type RequiredDraftField as Required} from "@/lib/inventory/draft-validation";
import {clearManualDrafts,loadManualDrafts,MANUAL_DRAFT_LIMIT,saveManualDrafts,type StoredDraft} from "@/lib/inventory/draft-storage";
import {createTranslator} from "@/lib/i18n/core";
import {locationDisplayName} from "@/lib/locations/display";
import {CameraBarcodeScanner} from "./camera-barcode-scanner";
import {CreatableCombobox} from "./creatable-combobox";
import {useI18n} from "./i18n-provider";
type Draft=StoredDraft; type Option={id:string;name:string;location_type?:string|null};
const input="mt-1.5 h-10 w-full min-w-0 rounded-lg border border-stone-300 bg-white px-3 text-sm focus:border-amber-700";
function price(d:DraftProduct){const w=Number(d.weight_grams),r=Number(d.price_per_gram);return d.weight_grams&&d.price_per_gram&&Number.isFinite(w)&&Number.isFinite(r)?w*r:null}
export function InventoryDraftBasket({ownerId,categories,producers,sizes,locations,warehouse}:{ownerId:string;categories:Option[];producers:string[];sizes:string[];locations:Option[];warehouse:Option|null}){
 const{t,locale}=useI18n(),first=useRef<HTMLInputElement>(null),barcode=useRef<HTMLInputElement>(null),refs=useRef<Partial<Record<Required,HTMLElement|null>>>({});
 const empty:DraftProduct={shop_id:warehouse?.id??"",category_name:"",article_number:"",producer:"",size:"",weight_grams:"",purchase_price:"",price_per_gram:"",barcode:""};
 const[entry,setEntry]=useState(empty),[drafts,setDrafts]=useState<Draft[]>([]),[restored,setRestored]=useState(false),[fieldErrors,setFieldErrors]=useState<ReturnType<typeof draftValidation>>({}),[rowErrors,setRowErrors]=useState<Record<number,string>>({}),[message,setMessage]=useState({error:"",success:""}),[documentId,setDocumentId]=useState<string|null>(null),[pending,startTransition]=useTransition();
 useEffect(()=>{let cancelled=false;const saved=loadManualDrafts(window.localStorage,ownerId),translate=createTranslator(locale);queueMicrotask(()=>{if(cancelled)return;setDrafts(current=>{const ids=new Set(current.map(d=>d.id));return [...current,...saved.filter(d=>!ids.has(d.id))]});if(saved.length)setMessage({error:"",success:translate("inventory.batch.restored",{count:saved.length})});setRestored(true)});return()=>{cancelled=true}},[locale,ownerId]);
 useEffect(()=>{if(!restored)return;const timer=window.setTimeout(()=>saveManualDrafts(window.localStorage,ownerId,drafts),250);return()=>window.clearTimeout(timer)},[drafts,ownerId,restored]);
 const set=(f:keyof DraftProduct,v:string)=>{setEntry(x=>({...x,[f]:v}));setFieldErrors(x=>({...x,[f]:undefined}))};
 function add(e:React.FormEvent){e.preventDefault();if(drafts.length>=MANUAL_DRAFT_LIMIT){setMessage({error:t("inventory.batch.limitReached",{count:MANUAL_DRAFT_LIMIT}),success:""});return}const next={...entry,barcode:normalizeScannedBarcode(entry.barcode)},invalid=draftValidation(next);setFieldErrors(invalid);const f=required.find(x=>invalid[x]);if(f){setMessage({error:"",success:""});refs.current[f]?.focus();return}if(next.barcode.length>200||(next.purchase_price!==""&&(!Number.isFinite(Number(next.purchase_price))||Number(next.purchase_price)<0))){setMessage({error:t("inventory.batch.rowInvalid",{row:drafts.length+1}),success:""});return}if(next.barcode&&drafts.some(d=>normalizeScannedBarcode(d.barcode)===next.barcode)){setMessage({error:t("inventory.batch.duplicateDraft",{row:drafts.length+1,barcode:next.barcode}),success:""});return}setDrafts(x=>[...x,{...next,id:crypto.randomUUID()}]);setEntry(x=>({...empty,shop_id:x.shop_id,category_name:x.category_name,producer:x.producer,price_per_gram:x.price_per_gram}));setMessage({error:"",success:""});queueMicrotask(()=>first.current?.focus())}
 function update(id:string,f:keyof DraftProduct,v:string){setDrafts(x=>x.map(d=>d.id===id?{...d,[f]:v}:d));setRowErrors({})}
 function clearBasket(){if(!window.confirm(t("inventory.batch.clearConfirm")))return;clearManualDrafts(window.localStorage,ownerId);setDrafts([]);setRowErrors({});setMessage({error:"",success:""})}
 function submit(){startTransition(async()=>{const result=await createInventoryBatch(drafts.map(d=>({shop_id:d.shop_id,category_name:d.category_name,article_number:d.article_number,producer:d.producer,size:d.size,weight_grams:d.weight_grams,purchase_price:d.purchase_price,price_per_gram:d.price_per_gram,barcode:d.barcode})));setRowErrors(result.rowErrors??{});setMessage({error:result.error,success:result.success??""});if(!result.error&&result.documentId){setDocumentId(result.documentId);clearManualDrafts(window.localStorage,ownerId);setDrafts([])}})}
 const cls=(f:Required)=>`${input} ${fieldErrors[f]?"border-red-600 ring-1 ring-red-600":""}`,err=(f:Required)=>fieldErrors[f]?<span className="mt-1 block text-xs text-red-700">{t(`errors.${fieldErrors[f]}`)}</span>:null;
 const lookup=(f:"category_name"|"producer"|"size",values:string[],label:string)=><label className="text-xs font-medium">{label}<CreatableCombobox label={label} inputRef={node=>{if(f==="category_name")first.current=node;if(f!=="size")refs.current[f]=node}} value={entry[f]} options={values} onChange={value=>set(f,value)} invalid={Boolean(fieldErrors[f as Required])}/>{f!=="size"?err(f):null}</label>;
 const edit=(d:Draft,f:keyof DraftProduct)=>{const numeric=["weight_grams","purchase_price","price_per_gram"].includes(f);return <input value={d[f]} onChange={e=>update(d.id,f,e.target.value)} onKeyDown={e=>{if(e.key==="Enter")e.preventDefault();if(e.key==="Escape")e.currentTarget.blur()}} type={numeric?"number":"text"} min="0" className={`h-8 w-full min-w-0 rounded border px-1 ${numeric?"text-right":""}`}/>};
 return <div className="space-y-6 [&>section]:border-stone-300 [&>section>div:first-child]:border-stone-300 [&>section>div:last-child]:border-stone-300"><form onSubmit={add} className="rounded-xl border bg-white p-4 shadow-sm sm:p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">
 {lookup("category_name",categories.map(x=>x.name),t("fields.productCategory"))}<label className="text-xs font-medium">{t("fields.article")}<input ref={n=>{refs.current.article_number=n}} value={entry.article_number} onChange={e=>set("article_number",e.target.value)} className={cls("article_number")}/>{err("article_number")}</label>{lookup("producer",producers,t("fields.producer"))}{lookup("size",sizes,t("fields.size"))}
 <label className="text-xs font-medium">{t("fields.weight")}<input ref={n=>{refs.current.weight_grams=n}} type="number" min="0.001" step="0.001" value={entry.weight_grams} onChange={e=>set("weight_grams",e.target.value)} className={cls("weight_grams")}/>{err("weight_grams")}</label><label className="text-xs font-medium">{t("fields.purchasePrice")}<input ref={n=>{refs.current.purchase_price=n}} type="number" min="0" step="0.01" value={entry.purchase_price} onChange={e=>set("purchase_price",e.target.value)} className={cls("purchase_price")}/>{err("purchase_price")}</label><label className="text-xs font-medium">{t("fields.pricePerGram")}<input ref={n=>{refs.current.price_per_gram=n}} type="number" min="0.01" step="0.01" value={entry.price_per_gram} onChange={e=>set("price_per_gram",e.target.value)} className={cls("price_per_gram")}/>{err("price_per_gram")}</label><div className="text-xs font-medium">{t("fields.priceUah")}<div className={`${input} flex items-center bg-stone-100`}>{formatPrice(price(entry),locale)}</div></div>
 <label className="text-xs font-medium lg:col-span-2">{t("fields.barcode")}<span className="mt-1.5 flex gap-2"><input ref={barcode} value={entry.barcode} maxLength={200} autoComplete="off" spellCheck={false} onChange={e=>set("barcode",e.target.value)} onBlur={e=>set("barcode",normalizeScannedBarcode(e.target.value))} onKeyDown={e=>{if(e.key==="Enter")e.preventDefault()}} className="h-10 min-w-0 flex-1 rounded-lg border border-stone-300 px-3 focus:border-amber-700 focus:outline-none focus:ring-2 focus:ring-amber-200"/><CameraBarcodeScanner returnFocus={barcode} onDetected={v=>set("barcode",v)}/></span></label><label className="text-xs font-medium lg:col-span-2">{t("fields.shop")}<select ref={n=>{refs.current.shop_id=n}} value={entry.shop_id} onChange={e=>set("shop_id",e.target.value)} className={cls("shop_id")}>{locations.map(x=><option key={x.id} value={x.id}>{locationDisplayName(x,locale)}</option>)}</select>{err("shop_id")}</label>
 </div><div className="mt-4 flex justify-end"><button className="rounded-lg bg-stone-900 px-5 py-2.5 text-sm font-semibold text-white">{t("inventory.batch.addToBasket")}</button></div></form>
 {message.error?<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{message.error}</p>:null}{message.success?<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{message.success}{documentId?<a className="ml-3 font-semibold underline" href={`/api/added-products/${documentId}/pdf`} download>{t("addedProducts.downloadPdf")}</a>:null}</p>:null}
 <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex items-center border-b bg-stone-50 px-4 py-3"><h2 className="font-semibold">{t("inventory.batch.productsToAdd")} ({drafts.length}/{MANUAL_DRAFT_LIMIT})</h2>{drafts.length?<button type="button" className="ml-auto text-sm text-red-700" onClick={clearBasket}>{t("inventory.batch.clearBasket")}</button>:null}</div>{drafts.length?<div className="overflow-x-auto"><table className="w-full table-fixed text-left text-xs"><thead><tr>{["number","productCategory","article","producer","size","weight","purchasePrice","pricePerGram","priceUah","shop","barcode","actions"].map((k,index)=><th className={`px-1.5 py-2 ${index===0||index===11?"w-9":""} ${index>=5&&index<=8?"text-right":""}`} key={k}>{k==="actions"?"":t(`fields.${k}`)}</th>)}</tr></thead><tbody>{drafts.map((d,i)=><tr key={d.id} className={rowErrors[i]?"bg-red-50":""}><td className="px-1.5">{i+1}</td>{(["category_name","article_number","producer","size","weight_grams","purchase_price","price_per_gram"] as (keyof DraftProduct)[]).map(f=><td className="p-0.5" key={f}>{edit(d,f)}</td>)}<td className="truncate px-1.5 text-right">{formatPrice(price(d),locale)}</td><td className="p-0.5"><select aria-label={t("fields.shop")} value={d.shop_id} onChange={e=>update(d.id,"shop_id",e.target.value)} className="h-8 w-full min-w-0 rounded border px-1">{locations.map(x=><option key={x.id} value={x.id}>{locationDisplayName(x,locale)}</option>)}</select></td><td className="p-0.5">{edit(d,"barcode")}{rowErrors[i]?<p className="text-[10px] text-red-700">{rowErrors[i]}</p>:null}</td><td className="px-1"><button type="button" aria-label={t("inventory.batch.remove")} title={t("inventory.batch.remove")} className="text-lg text-red-700" onClick={()=>setDrafts(x=>x.filter(y=>y.id!==d.id))}>×</button></td></tr>)}</tbody></table></div>:<p className="p-8 text-center text-sm text-stone-500">{t("inventory.batch.empty")}</p>}{drafts.length?<div className="flex justify-end border-t p-4"><button type="button" disabled={pending} onClick={submit} className="rounded-lg bg-stone-900 px-5 py-2.5 text-sm font-semibold text-white">{pending?t("common.saving"):t("inventory.batch.addProducts",{count:drafts.length})}</button></div>:null}</section></div>;
}
