"use client";
import {useRef,useState,useTransition} from "react";
import {createInventoryBatch,type DraftProduct} from "@/lib/inventory/actions";
import {formatPrice} from "@/lib/inventory/format";
import {normalizeScannedBarcode} from "@/lib/inventory/scanner";
import {draftValidation,requiredDraftFields as required,type RequiredDraftField as Required} from "@/lib/inventory/draft-validation";
import {locationDisplayName} from "@/lib/locations/display";
import {CameraBarcodeScanner} from "./camera-barcode-scanner";
import {useI18n} from "./i18n-provider";
type Draft=DraftProduct&{id:string}; type Option={id:string;name:string;location_type?:string|null};
const input="mt-1.5 h-10 w-full min-w-0 rounded-lg border border-stone-300 bg-white px-3 text-sm focus:border-amber-700";
function price(d:DraftProduct){const w=Number(d.weight_grams),r=Number(d.price_per_gram);return d.weight_grams&&d.price_per_gram&&Number.isFinite(w)&&Number.isFinite(r)?w*r:null}
export function InventoryDraftBasket({categories,producers,sizes,locations,warehouse}:{categories:Option[];producers:string[];sizes:string[];locations:Option[];warehouse:Option|null}){
 const{t,locale}=useI18n(),first=useRef<HTMLInputElement>(null),barcode=useRef<HTMLInputElement>(null),refs=useRef<Partial<Record<Required,HTMLElement|null>>>({});
 const empty:DraftProduct={shop_id:warehouse?.id??"",category_name:"",article_number:"",producer:"",size:"",weight_grams:"",purchase_price:"",price_per_gram:"",barcode:""};
 const[entry,setEntry]=useState(empty),[drafts,setDrafts]=useState<Draft[]>([]),[fieldErrors,setFieldErrors]=useState<ReturnType<typeof draftValidation>>({}),[rowErrors,setRowErrors]=useState<Record<number,string>>({}),[message,setMessage]=useState({error:"",success:""}),[pending,startTransition]=useTransition();
 const set=(f:keyof DraftProduct,v:string)=>{setEntry(x=>({...x,[f]:v}));setFieldErrors(x=>({...x,[f]:undefined}))};
 function add(e:React.FormEvent){e.preventDefault();const next={...entry,barcode:normalizeScannedBarcode(entry.barcode)},invalid=draftValidation(next);setFieldErrors(invalid);const f=required.find(x=>invalid[x]);if(f){setMessage({error:t("inventory.batch.requiredFields"),success:""});refs.current[f]?.focus();return}if(next.barcode.length>200||(next.purchase_price!==""&&(!Number.isFinite(Number(next.purchase_price))||Number(next.purchase_price)<0))){setMessage({error:t("inventory.batch.rowInvalid",{row:drafts.length+1}),success:""});return}if(next.barcode&&drafts.some(d=>normalizeScannedBarcode(d.barcode)===next.barcode)){setMessage({error:t("inventory.batch.duplicateDraft",{row:drafts.length+1,barcode:next.barcode}),success:""});return}setDrafts(x=>[...x,{...next,id:crypto.randomUUID()}]);setEntry(x=>({...empty,shop_id:x.shop_id,category_name:x.category_name,producer:x.producer,price_per_gram:x.price_per_gram}));setMessage({error:"",success:""});queueMicrotask(()=>first.current?.focus())}
 function update(id:string,f:keyof DraftProduct,v:string){setDrafts(x=>x.map(d=>d.id===id?{...d,[f]:v}:d));setRowErrors({})}
 function submit(){startTransition(async()=>{const result=await createInventoryBatch(drafts.map(d=>({shop_id:d.shop_id,category_name:d.category_name,article_number:d.article_number,producer:d.producer,size:d.size,weight_grams:d.weight_grams,purchase_price:d.purchase_price,price_per_gram:d.price_per_gram,barcode:d.barcode})));setRowErrors(result.rowErrors??{});setMessage({error:result.error,success:result.success??""});if(!result.error)setDrafts([])})}
 const cls=(f:Required)=>`${input} ${fieldErrors[f]?"border-red-600 ring-1 ring-red-600":""}`,err=(f:Required)=>fieldErrors[f]?<span className="mt-1 block text-xs text-red-700">{t(`validation.${fieldErrors[f]}`)}</span>:null;
 const lookup=(f:"category_name"|"producer"|"size",values:string[],label:string)=><label className="text-xs font-medium">{label}<input ref={node=>{if(f==="category_name")first.current=node;if(f!=="size")refs.current[f]=node}} list={`draft-${f}`} value={entry[f]} onChange={e=>set(f,e.target.value)} className={f==="size"?input:cls(f)} aria-invalid={Boolean(fieldErrors[f as Required])}/><datalist id={`draft-${f}`}>{values.map(v=><option key={v} value={v}/>)}</datalist>{f!=="size"?err(f):null}</label>;
 const edit=(d:Draft,f:keyof DraftProduct)=><input value={d[f]} onChange={e=>update(d.id,f,e.target.value)} onKeyDown={e=>{if(e.key==="Enter")e.preventDefault();if(e.key==="Escape")e.currentTarget.blur()}} type={["weight_grams","purchase_price","price_per_gram"].includes(f)?"number":"text"} min="0" className="h-8 min-w-24 rounded border px-2"/>;
 return <div className="space-y-6"><form onSubmit={add} className="rounded-xl border bg-white p-4 shadow-sm sm:p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">
 {lookup("category_name",categories.map(x=>x.name),t("fields.productCategory"))}<label className="text-xs font-medium">{t("fields.article")}<input value={entry.article_number} onChange={e=>set("article_number",e.target.value)} className={input}/></label>{lookup("producer",producers,t("fields.producer"))}{lookup("size",sizes,t("fields.size"))}
 <label className="text-xs font-medium">{t("fields.weight")}<input ref={n=>{refs.current.weight_grams=n}} type="number" min="0.001" step="0.001" value={entry.weight_grams} onChange={e=>set("weight_grams",e.target.value)} className={cls("weight_grams")}/>{err("weight_grams")}</label><label className="text-xs font-medium">{t("fields.purchasePrice")}<input type="number" min="0" step="0.01" value={entry.purchase_price} onChange={e=>set("purchase_price",e.target.value)} className={input}/></label><label className="text-xs font-medium">{t("fields.pricePerGram")}<input ref={n=>{refs.current.price_per_gram=n}} type="number" min="0.01" step="0.01" value={entry.price_per_gram} onChange={e=>set("price_per_gram",e.target.value)} className={cls("price_per_gram")}/>{err("price_per_gram")}</label><div className="text-xs font-medium">{t("fields.priceUah")}<div className={`${input} flex items-center bg-stone-100`}>{formatPrice(price(entry),locale)}</div></div>
 <label className="text-xs font-medium lg:col-span-2">{t("fields.barcode")}<span className="mt-1.5 flex gap-2"><input ref={barcode} value={entry.barcode} maxLength={200} autoComplete="off" spellCheck={false} onChange={e=>set("barcode",e.target.value)} onBlur={e=>set("barcode",normalizeScannedBarcode(e.target.value))} onKeyDown={e=>{if(e.key==="Enter")e.preventDefault()}} className="h-10 min-w-0 flex-1 rounded-lg border px-3"/><CameraBarcodeScanner returnFocus={barcode} onDetected={v=>set("barcode",v)}/></span></label><label className="text-xs font-medium lg:col-span-2">{t("fields.shop")}<select ref={n=>{refs.current.shop_id=n}} value={entry.shop_id} onChange={e=>set("shop_id",e.target.value)} className={cls("shop_id")}><option value="">{t("common.unassigned")}</option>{locations.map(x=><option key={x.id} value={x.id}>{locationDisplayName(x,locale)}</option>)}</select>{err("shop_id")}</label>
 </div><div className="mt-4 flex justify-end"><button className="rounded-lg bg-stone-900 px-5 py-2.5 text-sm font-semibold text-white">{t("inventory.batch.addToBasket")}</button></div></form>
 {message.error?<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{message.error}</p>:null}{message.success?<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{message.success}</p>:null}
 <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex items-center border-b bg-stone-50 px-4 py-3"><h2 className="font-semibold">{t("inventory.batch.productsToAdd")} ({drafts.length})</h2>{drafts.length?<button type="button" className="ml-auto text-sm text-red-700" onClick={()=>setDrafts([])}>{t("inventory.batch.clearBasket")}</button>:null}</div>{drafts.length?<div className="overflow-x-auto"><table className="w-full min-w-[1280px] text-left text-sm"><thead><tr>{["number","productCategory","article","producer","size","weight","purchasePrice","pricePerGram","priceUah","shop","barcode","actions"].map(k=><th className="px-3 py-2" key={k}>{k==="actions"?t("common.actions"):t(`fields.${k}`)}</th>)}</tr></thead><tbody>{drafts.map((d,i)=><tr key={d.id} className={rowErrors[i]?"bg-red-50":""}><td className="px-3">{i+1}</td>{(["category_name","article_number","producer","size","weight_grams","purchase_price","price_per_gram"] as (keyof DraftProduct)[]).map(f=><td className="p-1" key={f}>{edit(d,f)}</td>)}<td className="px-3">{formatPrice(price(d),locale)}</td><td className="px-3">{locationDisplayName(locations.find(x=>x.id===d.shop_id),locale)}</td><td className="p-1">{edit(d,"barcode")}{rowErrors[i]?<p className="text-xs text-red-700">{rowErrors[i]}</p>:null}</td><td className="px-3"><button type="button" className="text-red-700" onClick={()=>setDrafts(x=>x.filter(y=>y.id!==d.id))}>{t("inventory.batch.remove")}</button></td></tr>)}</tbody></table></div>:<p className="p-8 text-center text-sm text-stone-500">{t("inventory.batch.empty")}</p>}{drafts.length?<div className="flex justify-end border-t p-4"><button type="button" disabled={pending} onClick={submit} className="rounded-lg bg-stone-900 px-5 py-2.5 text-sm font-semibold text-white">{pending?t("common.saving"):t("inventory.batch.addProducts",{count:drafts.length})}</button></div>:null}</section></div>;
}
