"use client";
import {useRef,useState,useTransition} from "react";
import {createInventoryBatch,type DraftProduct} from "@/lib/inventory/actions";
import {formatPrice} from "@/lib/inventory/format";
import {locationDisplayName} from "@/lib/locations/display";
import {useI18n} from "./i18n-provider";

type Draft=DraftProduct&{id:string};
type Option={id:string;name:string;location_type?:string|null};
const blank:DraftProduct={category_name:"",article_number:"",producer:"",size:"",weight_grams:"",purchase_price:"",price_per_gram:"",barcode:""};
const input="mt-1.5 h-10 w-full min-w-0 rounded-lg border border-stone-300 bg-white px-3 text-sm focus:border-amber-700";
function price(draft:DraftProduct){const weight=Number(draft.weight_grams),rate=Number(draft.price_per_gram);return draft.weight_grams&&draft.price_per_gram&&Number.isFinite(weight)&&Number.isFinite(rate)?weight*rate:null}

export function InventoryDraftBasket({categories,warehouse}:{categories:Option[];warehouse:Option|null}){
 const{t,locale}=useI18n(),first=useRef<HTMLInputElement>(null);
 const[entry,setEntry]=useState<DraftProduct>(blank),[drafts,setDrafts]=useState<Draft[]>([]),[editing,setEditing]=useState(""),[editOriginal,setEditOriginal]=useState(""),[errors,setErrors]=useState<Record<number,string>>({}),[message,setMessage]=useState({error:"",success:""});
 const[pending,startTransition]=useTransition();
 function updateEntry(field:keyof DraftProduct,value:string){setEntry(current=>({...current,[field]:value}))}
 function add(event:React.FormEvent){event.preventDefault();const barcode=entry.barcode.trim(),numbers=[entry.weight_grams,entry.purchase_price,entry.price_per_gram];if(barcode.length>200||numbers.some(value=>value!==""&&(!Number.isFinite(Number(value))||Number(value)<0))){setMessage({error:t("inventory.batch.rowInvalid",{row:drafts.length+1}),success:""});return}if(barcode&&drafts.some(d=>d.barcode.trim()===barcode)){setMessage({error:t("inventory.batch.duplicateDraft",{row:drafts.length+1,barcode}),success:""});return}setDrafts(current=>[...current,{...entry,id:crypto.randomUUID()}]);setEntry(current=>({...blank,category_name:current.category_name,producer:current.producer,price_per_gram:current.price_per_gram}));setMessage({error:"",success:""});queueMicrotask(()=>first.current?.focus())}
 function update(id:string,field:keyof DraftProduct,value:string){setDrafts(current=>current.map(d=>d.id===id?{...d,[field]:value}:d));setErrors({});setMessage({error:"",success:""})}
 function submit(){startTransition(async()=>{const result=await createInventoryBatch(drafts.map(draft=>({category_name:draft.category_name,article_number:draft.article_number,producer:draft.producer,size:draft.size,weight_grams:draft.weight_grams,purchase_price:draft.purchase_price,price_per_gram:draft.price_per_gram,barcode:draft.barcode})));setErrors(result.rowErrors??{});setMessage({error:result.error,success:result.success??""});if(!result.error)setDrafts([])})}
 function editable(draft:Draft,field:keyof DraftProduct,row:number){const key=`${draft.id}:${field}`,value=draft[field];if(editing===key)return <input autoFocus value={value} onChange={e=>update(draft.id,field,e.target.value)} onBlur={()=>setEditing("")} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();setEditing("")}if(e.key==="Escape"){e.preventDefault();update(draft.id,field,editOriginal);setEditing("")}}} type={["weight_grams","purchase_price","price_per_gram"].includes(field)?"number":"text"} min="0" step={field==="weight_grams"?"0.001":"0.01"} className="h-8 min-w-24 rounded border px-2"/>;return <button type="button" className="min-h-8 w-full rounded px-1 text-left hover:bg-amber-50 focus-visible:outline-2" onClick={()=>{setEditOriginal(value);setEditing(key)}} aria-label={t("inventory.batch.editCell",{row:row+1})}>{value||"—"}</button>}
 return <div className="space-y-6">
  <form onSubmit={add} className="rounded-xl border border-stone-200 bg-white p-4 shadow-sm sm:p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">
   <label className="text-xs font-medium">{t("fields.productCategory")}<input ref={first} list="draft-category-options" value={entry.category_name} onChange={e=>updateEntry("category_name",e.target.value)} className={input}/><datalist id="draft-category-options">{categories.map(c=><option key={c.id} value={c.name}/>)}</datalist></label>
   <label className="text-xs font-medium">{t("fields.article")}<input value={entry.article_number} onChange={e=>updateEntry("article_number",e.target.value)} className={input}/></label><label className="text-xs font-medium">{t("fields.producer")}<input value={entry.producer} onChange={e=>updateEntry("producer",e.target.value)} className={input}/></label><label className="text-xs font-medium">{t("fields.size")}<input value={entry.size} onChange={e=>updateEntry("size",e.target.value)} className={input}/></label>
   <label className="text-xs font-medium">{t("fields.weight")}<input type="number" min="0" step="0.001" value={entry.weight_grams} onChange={e=>updateEntry("weight_grams",e.target.value)} className={input}/></label><label className="text-xs font-medium">{t("fields.purchasePrice")}<input type="number" min="0" step="0.01" value={entry.purchase_price} onChange={e=>updateEntry("purchase_price",e.target.value)} className={input}/></label><label className="text-xs font-medium">{t("fields.pricePerGram")}<input type="number" min="0" step="0.01" value={entry.price_per_gram} onChange={e=>updateEntry("price_per_gram",e.target.value)} className={input}/></label><div className="text-xs font-medium">{t("fields.priceUah")}<div className={`${input} flex items-center bg-stone-100`}>{formatPrice(price(entry),locale)}</div></div>
   <label className="text-xs font-medium lg:col-span-2">{t("fields.barcode")}<input value={entry.barcode} maxLength={200} onChange={e=>updateEntry("barcode",e.target.value)} className={input}/></label><div className="text-xs font-medium lg:col-span-2">{t("fields.shop")}<div className={`${input} flex items-center bg-stone-100`}>{warehouse?locationDisplayName(warehouse,locale):t("inventory.batch.warehouseMissing")}</div></div>
  </div><div className="mt-4 flex justify-end"><button className="rounded-lg bg-stone-900 px-5 py-2.5 text-sm font-semibold text-white">{t("inventory.batch.addToBasket")}</button></div></form>
  {message.error?<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{message.error}</p>:null}{message.success?<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{message.success}</p>:null}
  <section className="overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm" aria-label={t("inventory.batch.productsToAdd")}><div className="flex flex-wrap items-center gap-3 border-b bg-stone-50 px-4 py-3"><h2 className="font-semibold">{t("inventory.batch.productsToAdd")} ({drafts.length})</h2><span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-medium text-amber-900">{t("inventory.batch.draft")}</span>{drafts.length?<button type="button" className="ml-auto text-sm text-red-700" onClick={()=>{if(confirm(t("inventory.batch.clearConfirm"))){setDrafts([]);setErrors({})}}}>{t("inventory.batch.clearBasket")}</button>:null}</div>
   {drafts.length?<div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="border-b bg-stone-50 text-xs uppercase text-stone-500"><tr>{["number","productCategory","article","producer","size","weight","purchasePrice","pricePerGram","priceUah","barcode","actions"].map(k=><th className="px-3 py-2.5" key={k}>{k==="actions"?t("common.actions"):t(`fields.${k}`)}</th>)}</tr></thead><tbody className="divide-y">{drafts.map((d,row)=><tr key={d.id} className={errors[row]?"bg-red-50":""}><td className="px-3 py-2">{row+1}</td><td className="px-2 py-1">{editable(d,"category_name",row)}</td><td className="px-2 py-1">{editable(d,"article_number",row)}</td><td className="px-2 py-1">{editable(d,"producer",row)}</td><td className="px-2 py-1">{editable(d,"size",row)}</td><td className="px-2 py-1">{editable(d,"weight_grams",row)}</td><td className="px-2 py-1">{editable(d,"purchase_price",row)}</td><td className="px-2 py-1">{editable(d,"price_per_gram",row)}</td><td className="px-3 py-2 whitespace-nowrap">{formatPrice(price(d),locale)}</td><td className="px-2 py-1">{editable(d,"barcode",row)}{errors[row]?<p className="text-xs text-red-700">{errors[row]}</p>:null}</td><td className="px-3 py-2"><button type="button" className="text-red-700" onClick={()=>setDrafts(current=>current.filter(x=>x.id!==d.id))}>{t("inventory.batch.remove")}</button></td></tr>)}</tbody></table></div>:<p className="p-8 text-center text-sm text-stone-500">{t("inventory.batch.empty")}</p>}
   {drafts.length?<div className="flex justify-end border-t bg-stone-50 p-4"><button type="button" disabled={pending} onClick={submit} className="rounded-lg bg-stone-900 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{pending?t("common.saving"):t("inventory.batch.addProducts",{count:drafts.length})}</button></div>:null}
  </section>
 </div>;
}
