"use client";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useRef,useState,useTransition} from "react";
import type {Tables} from "@/lib/database.types";
import {bulkChangePricePerGram,bulkDeleteInventoryItems,bulkMoveInventoryItems} from "@/lib/inventory/actions";
import {InventoryStatus} from "@/components/inventory-status";
import {displayValue,formatDateTime,formatPrice} from "@/lib/inventory/format";
import {inventoryOrdinal} from "@/lib/inventory/pagination";
import {inventorySortHref} from "@/lib/inventory/filter-url";
import type {InventorySort,SortDirection} from "@/lib/inventory/queries";
import {locationDisplayName} from "@/lib/locations/display";
import {useI18n} from "./i18n-provider";
type Item=Tables<"inventory_items">&{product_categories:{name:string}|null;shops:{name:string;code:string|null;location_type:string}|null};
type Shop={id:string;name:string;location_type?:string|null};type Mode="move"|"price"|"delete";
export function InventoryBulkTable({items,shops,page,pageSize,count,canManage,currentQuery,sort,direction}:{items:Item[];shops:Shop[];page:number;pageSize:number;count:number;canManage:boolean;currentQuery:string;sort:InventorySort;direction:SortDirection}){
 const{t,locale}=useI18n(),router=useRouter(),dialog=useRef<HTMLDialogElement>(null);
 const[selected,setSelected]=useState<string[]>([]),[destination,setDestination]=useState(""),[rate,setRate]=useState(""),[mode,setMode]=useState<Mode>("move"),[state,setState]=useState({error:"",success:"",transferId:""});
 const[pending,startTransition]=useTransition(),allSelected=items.length>0&&selected.length===items.length;
 const sources=[...new Set(items.filter(x=>selected.includes(x.id)).map(x=>x.shop_id))],destinations=shops.filter(s=>sources.length!==1||s.id!==sources[0]);
 const columns=["number","productCategory","article","producer","size","weight",...(canManage?["purchasePrice"]:[]),"pricePerGram","priceUah","status","shop","barcode","createdDate"];
 const sortable=new Set(["number","productCategory","article","producer","size","weight","purchasePrice","pricePerGram","priceUah","shop","createdDate"]);
 function toggle(id:string){setSelected(x=>x.includes(id)?x.filter(y=>y!==id):[...x,id])}
 function open(next:Mode){setMode(next);dialog.current?.showModal()}
 function confirm(){dialog.current?.close();startTransition(async()=>{const result=mode==="move"?await bulkMoveInventoryItems(selected,destination||null):mode==="price"?await bulkChangePricePerGram(selected,rate):await bulkDeleteInventoryItems(selected);setState({error:result.error,success:result.success??"",transferId:result.transferId??""});if(!result.error){setSelected([]);setDestination("");router.refresh()}})}
 function header(k:string){if(!sortable.has(k))return t(`fields.${k}`);const next=sort===k&&direction==="asc"?"desc":"asc";return <Link className="inline-flex items-center gap-1 hover:text-stone-900" href={inventorySortHref(currentQuery,k,next)} scroll={false}>{t(`fields.${k}`)}{sort===k?<span aria-hidden="true">{direction==="asc"?"↑":"↓"}</span>:null}</Link>}
 return <><div className="flex flex-wrap items-center gap-3 border-b bg-stone-50 px-3 py-3">{canManage?<><button type="button" onClick={()=>setSelected(allSelected?[]:items.map(x=>x.id))} className="text-sm font-medium text-amber-900">{allSelected?t("inventory.clearSelection"):t("inventory.selectAll")}</button>{selected.length?<><span className="text-sm font-medium">{t("inventory.selected",{count:selected.length})}</span><select aria-label={t("inventory.destination")} value={destination} onChange={e=>setDestination(e.target.value)} className="ml-auto rounded-lg border px-3 py-2"><option value="">{t("inventory.selectLocation")}</option>{destinations.map(s=><option key={s.id} value={s.id}>{locationDisplayName(s,locale)}</option>)}</select><button disabled={!destination||pending} onClick={()=>open("move")} className="rounded-lg bg-stone-900 px-3 py-2 text-sm text-white">{t("inventory.moveSelected")}</button><button disabled={pending} onClick={()=>open("price")} className="rounded-lg border px-3 py-2 text-sm">{t("inventory.changeGramPrice")}</button><button disabled={pending} onClick={()=>open("delete")} className="rounded-lg bg-red-700 px-3 py-2 text-sm text-white">{t("inventory.deletePermanently")}</button></>:null}</>:null}</div>
 {state.error?<p role="alert" className="m-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{state.error}</p>:null}{state.success?<p role="status" className="m-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{state.success}{state.transferId?<Link className="ml-2 underline" href={`/transfers/${state.transferId}`}>{t("transfers.generate")}</Link>:null}</p>:null}
 <div className="overflow-x-auto"><table className="w-full min-w-[1380px] text-left text-sm"><thead className="border-b bg-stone-50 text-xs uppercase text-stone-500"><tr>{canManage?<th className="px-3 py-3"/>:null}{columns.map(k=><th key={k} className="px-3 py-3">{header(k)}</th>)}</tr></thead><tbody className="divide-y">{items.map((item,index)=><tr key={item.id}>{canManage?<td className="px-3 py-3"><input type="checkbox" checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/></td>:null}<td className="px-3 py-3"><Link href={`/inventory/${item.id}`}>{direction==="desc"&&sort==="number"?count-inventoryOrdinal(page,pageSize,index)+1:inventoryOrdinal(page,pageSize,index)}</Link></td><td className="px-3 py-3">{item.product_categories?.name??"—"}</td><td className="px-3 py-3">{displayValue(item.article_number)}</td><td className="px-3 py-3">{displayValue(item.producer)}</td><td className="px-3 py-3">{displayValue(item.size)}</td><td className="px-3 py-3">{item.weight_grams??"—"}</td>{canManage?<td className="px-3 py-3">{formatPrice(item.purchase_price,locale)}</td>:null}<td className="px-3 py-3">{formatPrice(item.price_per_gram,locale)}</td><td className="px-3 py-3">{formatPrice(item.price,locale)}</td><td className="px-3 py-3"><InventoryStatus status={item.status}/></td><td className="px-3 py-3">{locationDisplayName(item.shops,locale)??t("common.unassigned")}</td><td className="px-3 py-3">{displayValue(item.barcode)}</td><td className="whitespace-nowrap px-3 py-3">{formatDateTime(item.created_at,locale)}</td></tr>)}</tbody></table></div>
 <dialog ref={dialog} aria-labelledby="bulk-dialog-title" aria-describedby="bulk-dialog-description" className="m-auto w-[calc(100%-2rem)] max-w-md rounded-2xl border border-stone-200 bg-white p-0 shadow-2xl backdrop:bg-black/50"><div className="p-6"><h2 id="bulk-dialog-title" className="text-xl font-semibold text-stone-950">{t(`inventory.bulk.${mode}Title`,{count:selected.length})}</h2><p id="bulk-dialog-description" className="mt-3 text-sm leading-6 text-stone-600">{t(`inventory.bulk.${mode}Description`,{count:selected.length})}</p>{mode==="price"?<label className="mt-5 block text-sm font-medium">{t("fields.pricePerGram")}<input className="mt-2 w-full rounded-lg border border-stone-300 px-3 py-2.5" type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/></label>:null}</div><div className="flex justify-end gap-3 border-t border-stone-200 bg-stone-50 px-6 py-4"><button type="button" className="rounded-lg border border-stone-300 bg-white px-4 py-2 text-sm font-semibold text-stone-700 hover:bg-stone-100" onClick={()=>dialog.current?.close()}>{t("common.cancel")}</button><button type="button" className={mode==="delete"?"rounded-lg bg-red-700 px-4 py-2 text-sm font-semibold text-white hover:bg-red-800 disabled:opacity-50":"rounded-lg bg-stone-900 px-4 py-2 text-sm font-semibold text-white hover:bg-stone-700 disabled:opacity-50"} onClick={confirm} disabled={mode==="price"&&(!rate||Number(rate)<0)}>{mode==="delete"?t("inventory.deletePermanently"):t("common.confirm")}</button></div></dialog></>;
}
