"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useRef, useState, useTransition } from "react";
import type { Tables } from "@/lib/database.types";
import { bulkMoveInventoryItems } from "@/lib/inventory/actions";
import { InventoryStatus } from "@/components/inventory-status";
import { displayValue, formatPrice } from "@/lib/inventory/format";
import { inventoryOrdinal } from "@/lib/inventory/pagination";
import { useI18n } from "./i18n-provider";

type Item=Tables<"inventory_items">&{product_categories:{name:string}|null;shops:{name:string;code:string|null}|null};
type Shop={id:string;name:string};
export function InventoryBulkTable({items,shops,page,pageSize,canManage}:{items:Item[];shops:Shop[];page:number;pageSize:number;canManage:boolean}){
  const {t,locale}=useI18n();
  const router=useRouter();const[selected,setSelected]=useState<string[]>([]);const[destination,setDestination]=useState("");const[state,setState]=useState({error:"",success:""});const[pending,startTransition]=useTransition();const dialog=useRef<HTMLDialogElement>(null);
  const allSelected=items.length>0&&selected.length===items.length;
  function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);setState({error:"",success:""});}
  function confirm(){dialog.current?.close();startTransition(async()=>{const result=await bulkMoveInventoryItems(selected,destination||null);setState({error:result.error,success:result.success??""});if(!result.error){setSelected([]);router.refresh();}});}
  return <>
    {canManage?<div className="flex flex-wrap items-center gap-3 border-b border-stone-200 bg-stone-50 px-4 py-3"><button type="button" onClick={()=>setSelected(allSelected?[]:items.map(item=>item.id))} className="text-sm font-medium text-amber-900">{allSelected?t("inventory.clearSelection"):t("inventory.selectAll")}</button>{selected.length?<><button type="button" onClick={()=>setSelected([])} className="text-sm text-stone-600">{t("inventory.clearSelection")}</button><span className="text-sm font-medium">{t("inventory.selected",{count:selected.length})}</span><label className="ml-auto text-sm font-medium">{t("inventory.moveToShop")} <select aria-label={t("inventory.destination")} value={destination} onChange={event=>setDestination(event.target.value)} className="ml-2 rounded-lg border border-stone-300 bg-white px-3 py-2"><option value="">{t("common.unassigned")}</option>{shops.map(shop=><option key={shop.id} value={shop.id}>{shop.name}</option>)}</select></label><button type="button" disabled={pending} onClick={()=>dialog.current?.showModal()} className="rounded-lg bg-stone-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{pending?t("inventory.moving"):t("inventory.moveSelected")}</button></>:null}</div>:null}
    {state.error?<p role="alert" className="m-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{state.error}</p>:null}{state.success?<p role="status" className="m-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{state.success}</p>:null}
    <div className="overflow-x-auto"><table className={`${canManage?"min-w-[1660px]":"min-w-[1600px]"} w-full text-left text-sm`}><thead className="border-b border-stone-200 bg-stone-50 text-xs uppercase tracking-wide text-stone-500"><tr>{canManage?<th className="px-4 py-3"><span className="sr-only">{t("common.actions")}</span></th>:null}{["number","productCategory","producer","metal","fineness","size","weight","pricePerGram","article","priceUah","notes","status","shop","barcode"].map(key=><th key={key} className="px-4 py-3 font-medium">{t(`fields.${key}`)}</th>)}</tr></thead><tbody className="divide-y divide-stone-100">{items.map((item,index)=><tr key={item.id} className="hover:bg-amber-50/40">{canManage?<td className="px-4 py-3"><input type="checkbox" aria-label={t("inventory.selectProduct",{number:inventoryOrdinal(page,pageSize,index)})} checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/></td>:null}<td className="px-4 py-3 font-medium"><Link href={`/inventory/${item.id}`} className="text-amber-900 underline-offset-4 hover:underline">{inventoryOrdinal(page,pageSize,index)}</Link></td><td className="px-4 py-3">{item.product_categories?.name??"—"}</td><td className="px-4 py-3">{displayValue(item.producer)}</td><td className="px-4 py-3">{displayValue(item.metal)}</td><td className="px-4 py-3">{displayValue(item.gold_fineness)}</td><td className="px-4 py-3">{displayValue(item.size)}</td><td className="px-4 py-3">{item.weight_grams===null?"—":`${item.weight_grams} ${t("common.grams")}`}</td><td className="px-4 py-3 whitespace-nowrap">{formatPrice(item.price_per_gram,locale)}</td><td className="px-4 py-3">{displayValue(item.article_number)}</td><td className="px-4 py-3 whitespace-nowrap">{formatPrice(item.price,locale)}</td><td className="max-w-80 px-4 py-3"><span className="line-clamp-2">{displayValue(item.notes)}</span></td><td className="px-4 py-3"><InventoryStatus status={item.status}/></td><td className="px-4 py-3">{item.shops?.name??t("common.unassigned")}</td><td className="px-4 py-3 font-medium">{displayValue(item.barcode)}</td></tr>)}</tbody></table></div>
    <dialog ref={dialog} className="m-auto w-[calc(100%-2rem)] max-w-md rounded-xl border bg-white p-6 shadow-2xl backdrop:bg-stone-950/50"><h2 className="text-xl font-semibold">{t("inventory.moveTitle")}</h2><p className="mt-3 text-sm text-stone-600">{t("inventory.moveDescription",{count:selected.length,shop:shops.find(shop=>shop.id===destination)?.name??t("common.unassigned")})}</p><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>dialog.current?.close()} className="px-4 py-2 text-sm">{t("common.cancel")}</button><button type="button" onClick={confirm} className="rounded-lg bg-stone-900 px-4 py-2 text-sm font-medium text-white">{t("inventory.confirmMove")}</button></div></dialog>
  </>;
}
