import {readFileSync} from "node:fs";
import {describe,expect,it} from "vitest";
const read=(path:string)=>readFileSync(new URL(path,import.meta.url),"utf8");
describe("Created Date and manual batch workflow",()=>{
 it("renders Created Date after Barcode and database-sorts before pagination",()=>{const table=read("./inventory-bulk-table.tsx"),query=read("../lib/inventory/queries.ts");expect(table.indexOf('"barcode","createdDate"')).toBeGreaterThan(-1);expect(table).toContain("formatDateTime(item.created_at,locale)");expect(query).toContain('createdDate: "created_at"');expect(query.indexOf('.order(inventorySortColumns[sort]')).toBeLessThan(query.indexOf('.range(from, from + pageSize - 1)'))});
 it("keeps Barcode and Article empty without placeholders",()=>{const filters=read("./inventory-filters.tsx");expect(filters).not.toContain("placeholder=");expect(filters).toContain('type="date"')});
 it("uses Revenue as the primary metric with subordinate profit, items and weight",()=>{const page=read("../app/(protected)/dashboard/page.tsx"),start=page.indexOf('aria-labelledby="statistics-title"'),end=page.indexOf("data-dashboard-inventory"),kpis=page.slice(start,end);expect(kpis.indexOf("dashboard.revenue")).toBeLessThan(kpis.indexOf("dashboard.netProfit"));expect(kpis.indexOf("dashboard.netProfit")).toBeLessThan(kpis.indexOf("dashboard.itemsSold"));expect(kpis.indexOf("dashboard.itemsSold")).toBeLessThan(kpis.indexOf("dashboard.goldWeightSold"))});
 it("uses editable local drafts, removal and one atomic final action",()=>{const basket=read("./inventory-draft-basket.tsx"),action=read("../lib/inventory/actions.ts"),migration=read("../../supabase/migrations/20260915180000_manual_batch_selectable_location.sql");expect(basket).toContain("setDrafts");expect(basket).toContain('e.key==="Escape"');expect(basket).toContain("createInventoryBatch");expect(basket).toContain("filter(y=>y.id!==d.id)");expect(action).toContain('rpc("create_inventory_items_batch"');expect(migration).toContain("require_owner_employee");expect(migration).toContain("is_active");expect(migration).toContain("for v_item");expect(migration).toContain("Row %s")});
});
