/* eslint-disable @next/next/no-img-element */
import {documentWeightUnit,formatDocumentDateTime,formatDocumentPrice,formatDocumentTotalPrice} from "@/lib/documents/format";
export type TransferNoteData={transfer_number:string;transferred_at:string;source_name:string;destination_name:string;source_address:string|null;destination_address:string|null;performed_by_name:string;item_count:number;total_weight:number;total_value:number};
export type TransferNoteItem={id?:string;line_number:number;category_name:string|null;article_number:string|null;producer:string|null;size:string|null;weight_grams:number|null;price_per_gram:number|null;price:number|null;barcode:string|null};
export type TransferNoteLabels={title:string;number:string;date:string;from:string;to:string;itemCount:string;totalWeight:string;totalValue:string;performedBy:string;sender:string;receiver:string;headings:string[]};
export type DocumentWebPresentation={formatPrice:(value:number|null)=>string;formatWeight:(value:number)=>string};

export const TRANSFER_NOTE_CSS=String.raw`
.transfer-note,.transfer-note *{box-sizing:border-box}
.transfer-note{max-width:1120px;margin:0 auto;padding:32px;background:#fff;color:#2f2118;font-family:"Zlata Currency",Arial,Helvetica,sans-serif;font-size:14px;line-height:1.4}
.transfer-note__header{display:grid;grid-template-columns:160px minmax(180px,1fr) minmax(240px,auto);align-items:center;gap:20px;padding-bottom:18px;border-bottom:2px solid #785115}
.transfer-note__logo{display:block;width:120px;height:48px;object-fit:contain;object-position:left center}
.transfer-note__heading{margin:0;color:#352109;font-family:Georgia,"Times New Roman",serif;font-size:26px;font-weight:600;line-height:1.15;text-align:center;text-transform:none}
.transfer-note__meta{min-width:240px;text-align:right}.transfer-note__meta strong,.transfer-note__meta span{display:block;white-space:nowrap}.transfer-note__meta strong{color:#57370b}.transfer-note__meta span{margin-top:3px;color:#665542;font-size:12px}.transfer-note__number{display:inline!important;margin:0!important;color:inherit!important;font-size:inherit!important}
.transfer-note__locations{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:20px}.transfer-note__location{padding:12px 14px;border:1px solid #d0c1ac;border-radius:8px;background:#faf7f1}.transfer-note__location-label{display:block;margin-bottom:6px;color:#785115;font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.transfer-note__location-name{display:block;font-size:16px}.transfer-note__address{display:block;margin-top:4px;color:#665542;font-size:12px}
.transfer-note__table-wrap{margin-top:20px}.transfer-note__table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:12px;font-variant-numeric:tabular-nums}.transfer-note__table th,.transfer-note__table td{padding:6px 5px;border:1px solid #d0c1ac;word-break:normal;vertical-align:top}.transfer-note__table th{background:#f2ece1;color:#402a15;font-size:13px;font-weight:700;line-height:1.15;text-align:center;overflow-wrap:normal;word-break:keep-all;hyphens:none}.transfer-note__heading-main,.transfer-note__heading-unit{display:block}.transfer-note__heading-unit{white-space:nowrap}.transfer-note__col--nr{width:3.5%}.transfer-note__col--category{width:15%}.transfer-note__col--article{width:8.5%}.transfer-note__col--producer{width:14%}.transfer-note__col--size{width:7.5%}.transfer-note__col--weight{width:6.5%}.transfer-note__col--price-per-gram{width:16%}.transfer-note__col--price{width:14.5%}.transfer-note__col--barcode{width:14.5%}.transfer-note__table td.transfer-note__cell--nr,.transfer-note__table td.transfer-note__cell--size,.transfer-note__table td.transfer-note__cell--weight,.transfer-note__table td.transfer-note__cell--price-per-gram,.transfer-note__table td.transfer-note__cell--price{text-align:right;white-space:nowrap}.transfer-note__cell--category,.transfer-note__cell--producer{overflow-wrap:break-word}.transfer-note__cell--article,.transfer-note__cell--barcode{overflow-wrap:anywhere}.transfer-note__cell--barcode{text-overflow:clip}.transfer-note--compact-table .transfer-note__table{font-size:11px}.transfer-note--compact-table .transfer-note__table th{font-size:11px}.transfer-note--compact-table .transfer-note__table th,.transfer-note--compact-table .transfer-note__table td{padding:5px 3px}
.transfer-note--ua-table .transfer-note__table{table-layout:auto}.transfer-note--ua-table .transfer-note__table th,.transfer-note--ua-table .transfer-note__table td{padding:5px 4px}.transfer-note--ua-table .transfer-note__col--category,.transfer-note--ua-table .transfer-note__col--article,.transfer-note--ua-table .transfer-note__col--producer,.transfer-note--ua-table .transfer-note__col--barcode{width:auto}.transfer-note--ua-table .transfer-note__col--nr,.transfer-note--ua-table .transfer-note__col--size,.transfer-note--ua-table .transfer-note__col--weight,.transfer-note--ua-table .transfer-note__col--price-per-gram,.transfer-note--ua-table .transfer-note__col--price{width:1%}.transfer-note--ua-table .transfer-note__cell--nr,.transfer-note--ua-table .transfer-note__cell--size,.transfer-note--ua-table .transfer-note__cell--weight,.transfer-note--ua-table .transfer-note__cell--price-per-gram,.transfer-note--ua-table .transfer-note__cell--price{white-space:nowrap}.transfer-note--ua-table .transfer-note__cell--category,.transfer-note--ua-table .transfer-note__cell--producer{overflow-wrap:normal;word-break:normal}.transfer-note--ua-table .transfer-note__table td.transfer-note__cell--article{white-space:nowrap;overflow-wrap:normal}.transfer-note--ua-table .transfer-note__cell--barcode{white-space:nowrap;overflow-wrap:normal;word-break:normal}.transfer-note--ua-table .transfer-note__cell--barcode.transfer-note__cell--long-id{white-space:normal;overflow-wrap:anywhere}
.transfer-note--ua-table .transfer-note__table td.transfer-note__cell--price-per-gram,.transfer-note--ua-table .transfer-note__table td.transfer-note__cell--price{text-align:right}
.transfer-note__summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:20px;padding-top:14px;border-top:2px solid #785115}.transfer-note__summary div{padding:10px;background:#faf7f1}.transfer-note__summary span,.transfer-note__summary strong{display:block;font-size:13px}.transfer-note__summary span{color:#665542;font-weight:500}.transfer-note__summary strong{margin-top:3px;color:#352109;font-weight:700}.transfer-note__performed{margin:16px 0 0}.transfer-note__signatures{display:grid;grid-template-columns:1fr 1fr;gap:64px;margin-top:62px;padding-bottom:10px}.transfer-note__signature{padding-top:8px;border-top:1px solid #523c27;color:#665542;font-size:12px}
@page{size:A4 portrait;margin:12mm}
@media print{html,body{background:#fff!important}body::before,body>a,body>header,.transfer-note-actions{display:none!important}main#main-content{width:auto!important;max-width:none!important;margin:0!important;padding:0!important}.transfer-note{width:100%;max-width:none;margin:0;padding:0;font-size:9pt;print-color-adjust:exact;-webkit-print-color-adjust:exact}.transfer-note__header{grid-template-columns:30mm 1fr minmax(48mm,auto);gap:4mm;padding-bottom:4mm}.transfer-note__logo{width:28mm;height:12mm}.transfer-note__heading{font-size:16pt}.transfer-note__locations{gap:4mm;margin-top:4mm}.transfer-note__location{padding:2.5mm 3.5mm;border-radius:1.5mm}.transfer-note__table-wrap{margin-top:4mm;overflow:visible}.transfer-note__table{font-size:9pt}.transfer-note--compact-table .transfer-note__table{font-size:8.25pt}.transfer-note__table thead{display:table-header-group}.transfer-note__table tr{break-inside:avoid;page-break-inside:avoid}.transfer-note__table th,.transfer-note__table td{padding:1.2mm .8mm}.transfer-note__table th{font-size:9.75pt}.transfer-note--compact-table .transfer-note__table th{font-size:8.5pt;padding-right:.7mm;padding-left:.7mm}.transfer-note--ua-table .transfer-note__table th,.transfer-note--ua-table .transfer-note__table td{padding:1.1mm .7mm}.transfer-note__summary,.transfer-note__performed,.transfer-note__signatures{break-inside:avoid;page-break-inside:avoid}.transfer-note__summary{gap:3mm;margin-top:4mm;padding-top:3mm}.transfer-note__summary div{padding:2.5mm}.transfer-note__summary span,.transfer-note__summary strong{font-size:9.75pt}.transfer-note__signatures{gap:16mm;margin-top:15mm}}
`;

const display=(value:unknown)=>value===null||value===undefined||value===""?"—":String(value);
export const TRANSFER_NOTE_COLUMNS=["nr","category","article","producer","size","weight","price-per-gram","price","barcode"] as const;
export function DocumentTableHeading({heading}:{heading:string}){
 const match=heading.match(/^(.*)\s+(\((?:UAH|грн)\))$/u);
 return <><span className="transfer-note__heading-main">{match?.[1]??heading}</span>{match?<span className="transfer-note__heading-unit">{match[2]}</span>:null}</>;
}
export function TransferNote({transfer,items,labels,locale,logoSrc,presentation}:{transfer:TransferNoteData;items:TransferNoteItem[];labels:TransferNoteLabels;locale:"ua"|"en";logoSrc:string;presentation?:DocumentWebPresentation}){
 const language=locale==="ua"?"uk-UA":"en-US",number=new Intl.NumberFormat(language,{maximumFractionDigits:3}),date=formatDocumentDateTime(transfer.transferred_at,locale),weightUnit=documentWeightUnit(locale),formatCellPrice=(value:number)=>presentation?.formatPrice(value)??formatDocumentPrice(value,locale),formatTotalPrice=(value:number)=>presentation?.formatPrice(value)??formatDocumentTotalPrice(value,locale),formatWeight=(value:number)=>presentation?.formatWeight(value)??number.format(value),totalValue=formatTotalPrice(transfer.total_value);
 const compact=locale==="en"&&items.some(item=>[item.category_name,item.article_number,item.producer,item.barcode].some(value=>(value?.length??0)>24)||String(item.price_per_gram??"").length>12||String(item.price??"").length>12);
 return <><style dangerouslySetInnerHTML={{__html:TRANSFER_NOTE_CSS}}/><article className={`transfer-note${locale==="ua"?" transfer-note--ua-table":""}${compact?" transfer-note--compact-table":""}`} lang={locale==="ua"?"uk":"en"}><header className="transfer-note__header"><img className="transfer-note__logo" src={logoSrc} alt="Zlata Jewelry"/><h1 className="transfer-note__heading">{labels.title}</h1><div className="transfer-note__meta"><strong>{labels.number}: <span className="transfer-note__number">{transfer.transfer_number}</span></strong><span>{labels.date}: {date}</span></div></header><section className="transfer-note__locations"><div className="transfer-note__location"><span className="transfer-note__location-label">{labels.from}</span><strong className="transfer-note__location-name">{transfer.source_name}</strong>{transfer.source_address?<span className="transfer-note__address">{transfer.source_address}</span>:null}</div><div className="transfer-note__location"><span className="transfer-note__location-label">{labels.to}</span><strong className="transfer-note__location-name">{transfer.destination_name}</strong>{transfer.destination_address?<span className="transfer-note__address">{transfer.destination_address}</span>:null}</div></section><div className="transfer-note__table-wrap"><table className="transfer-note__table"><colgroup>{TRANSFER_NOTE_COLUMNS.map(column=><col key={column} className={`transfer-note__col--${column}`}/>)}</colgroup><thead><tr>{labels.headings.map((heading,index)=><th key={heading} className={`transfer-note__cell--${TRANSFER_NOTE_COLUMNS[index]}`}><DocumentTableHeading heading={heading}/></th>)}</tr></thead><tbody>{items.map(item=><tr key={item.id??item.line_number}>{[item.line_number,item.category_name,item.article_number,item.producer,item.size,item.weight_grams,item.price_per_gram,item.price,item.barcode].map((value,index)=><td key={index} className={`transfer-note__cell--${TRANSFER_NOTE_COLUMNS[index]}${index===8&&typeof value==="string"&&value.length>13?" transfer-note__cell--long-id":""}`}>{index>=6&&index<=7&&typeof value==="number"?formatCellPrice(value):index===5&&typeof value==="number"?formatWeight(value):display(value)}</td>)}</tr>)}</tbody></table></div><section className="transfer-note__summary"><div><span>{labels.itemCount}</span><strong>{transfer.item_count}</strong></div><div><span>{labels.totalWeight}</span><strong>{formatWeight(transfer.total_weight)}{presentation?"":` ${weightUnit}`}</strong></div><div><span>{labels.totalValue}</span><strong>{totalValue}</strong></div></section><p className="transfer-note__performed"><strong>{labels.performedBy}:</strong> {transfer.performed_by_name}</p><section className="transfer-note__signatures"><div className="transfer-note__signature">{labels.sender}</div><div className="transfer-note__signature">{labels.receiver}</div></section></article></>;
}
