/* eslint-disable @next/next/no-img-element */
export type TransferNoteData={transfer_number:string;transferred_at:string;source_name:string;destination_name:string;source_address:string|null;destination_address:string|null;performed_by_name:string;item_count:number;total_weight:number;total_value:number};
export type TransferNoteItem={id?:string;line_number:number;category_name:string|null;article_number:string|null;producer:string|null;size:string|null;weight_grams:number|null;price_per_gram:number|null;price:number|null;barcode:string|null};
export type TransferNoteLabels={title:string;number:string;date:string;from:string;to:string;itemCount:string;totalWeight:string;totalValue:string;performedBy:string;sender:string;receiver:string;headings:string[]};

export const TRANSFER_NOTE_CSS=String.raw`
.transfer-note,.transfer-note *{box-sizing:border-box}
.transfer-note{max-width:1120px;margin:0 auto;padding:32px;background:#fff;color:#2f2118;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.4}
.transfer-note__header{display:grid;grid-template-columns:160px minmax(180px,1fr) minmax(240px,auto);align-items:center;gap:20px;padding-bottom:18px;border-bottom:2px solid #785115}
.transfer-note__logo{display:block;width:120px;height:48px;object-fit:contain;object-position:left center}
.transfer-note__heading{margin:0;color:#352109;font-family:Georgia,"Times New Roman",serif;font-size:26px;font-weight:600;line-height:1.15;text-align:center;text-transform:none}
.transfer-note__meta{min-width:240px;text-align:right}.transfer-note__meta strong,.transfer-note__meta span{display:block;white-space:nowrap}.transfer-note__meta strong{color:#57370b}.transfer-note__meta span{margin-top:3px;color:#665542;font-size:12px}.transfer-note__number{display:inline!important;margin:0!important;color:inherit!important;font-size:inherit!important}
.transfer-note__locations{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:20px}.transfer-note__location{padding:12px 14px;border:1px solid #d0c1ac;border-radius:8px;background:#faf7f1}.transfer-note__location-label{display:block;margin-bottom:6px;color:#785115;font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.transfer-note__location-name{display:block;font-size:16px}.transfer-note__address{display:block;margin-top:4px;color:#665542;font-size:12px}
.transfer-note__table-wrap{margin-top:20px}.transfer-note__table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:12px;font-variant-numeric:tabular-nums}.transfer-note__table th,.transfer-note__table td{padding:6px 5px;border:1px solid #d0c1ac;overflow-wrap:anywhere;vertical-align:top}.transfer-note__table th{background:#f2ece1;color:#402a15;font-size:13px;font-weight:700;line-height:1.2;text-align:left}.transfer-note__table th:first-child,.transfer-note__table td:first-child{width:4%;text-align:right}.transfer-note__table th:nth-child(2){width:15%}.transfer-note__table th:nth-child(3){width:11%}.transfer-note__table th:nth-child(4){width:14%}.transfer-note__table th:nth-child(5){width:8%}.transfer-note__table th:nth-child(6){width:9%}.transfer-note__table th:nth-child(7){width:12%}.transfer-note__table th:nth-child(8){width:12%}.transfer-note__table th:nth-child(9){width:15%}.transfer-note__table td:nth-child(n+5){white-space:nowrap;overflow-wrap:normal}.transfer-note__table th:nth-child(n+6):nth-child(-n+8),.transfer-note__table td:nth-child(n+6):nth-child(-n+8){text-align:right}
.transfer-note__table th:nth-child(9),.transfer-note__table td:nth-child(9){white-space:normal;overflow-wrap:anywhere;word-break:break-all}
.transfer-note__summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:20px;padding-top:14px;border-top:2px solid #785115}.transfer-note__summary div{padding:10px;background:#faf7f1}.transfer-note__summary span,.transfer-note__summary strong{display:block;font-size:13px}.transfer-note__summary span{color:#665542;font-weight:500}.transfer-note__summary strong{margin-top:3px;color:#352109;font-weight:700}.transfer-note__performed{margin:16px 0 0}.transfer-note__signatures{display:grid;grid-template-columns:1fr 1fr;gap:64px;margin-top:62px;padding-bottom:10px}.transfer-note__signature{padding-top:8px;border-top:1px solid #523c27;color:#665542;font-size:12px}
@page{size:A4 portrait;margin:12mm}
@media print{html,body{background:#fff!important}body::before,body>a,body>header,.transfer-note-actions{display:none!important}main#main-content{width:auto!important;max-width:none!important;margin:0!important;padding:0!important}.transfer-note{width:100%;max-width:none;margin:0;padding:0;font-size:9pt;print-color-adjust:exact;-webkit-print-color-adjust:exact}.transfer-note__header{grid-template-columns:30mm 1fr minmax(48mm,auto);gap:4mm;padding-bottom:4mm}.transfer-note__logo{width:28mm;height:12mm}.transfer-note__heading{font-size:16pt}.transfer-note__locations{gap:4mm;margin-top:4mm}.transfer-note__location{padding:2.5mm 3.5mm;border-radius:1.5mm}.transfer-note__table-wrap{margin-top:4mm;overflow:visible}.transfer-note__table{font-size:9pt}.transfer-note__table thead{display:table-header-group}.transfer-note__table tr{break-inside:avoid;page-break-inside:avoid}.transfer-note__table th,.transfer-note__table td{padding:1.2mm .8mm}.transfer-note__table th{font-size:9.75pt}.transfer-note__summary,.transfer-note__performed,.transfer-note__signatures{break-inside:avoid;page-break-inside:avoid}.transfer-note__summary{gap:3mm;margin-top:4mm;padding-top:3mm}.transfer-note__summary div{padding:2.5mm}.transfer-note__summary span,.transfer-note__summary strong{font-size:9.75pt}.transfer-note__signatures{gap:16mm;margin-top:15mm}}
`;

const display=(value:unknown)=>value===null||value===undefined||value===""?"—":String(value);
export function TransferNote({transfer,items,labels,locale,logoSrc}:{transfer:TransferNoteData;items:TransferNoteItem[];labels:TransferNoteLabels;locale:"ua"|"en";logoSrc:string}){
 const language=locale==="ua"?"uk-UA":"en-US",number=new Intl.NumberFormat(language,{maximumFractionDigits:2}),money=new Intl.NumberFormat(language,{style:"currency",currency:"UAH"}),date=new Intl.DateTimeFormat(language,{dateStyle:"long",timeStyle:"short",timeZone:"Europe/Kyiv"}).format(new Date(transfer.transferred_at));
 return <><style dangerouslySetInnerHTML={{__html:TRANSFER_NOTE_CSS}}/><article className="transfer-note" lang={locale==="ua"?"uk":"en"}><header className="transfer-note__header"><img className="transfer-note__logo" src={logoSrc} alt="Zlata Jewelry"/><h1 className="transfer-note__heading">{labels.title}</h1><div className="transfer-note__meta"><strong>{labels.number}: <span className="transfer-note__number">{transfer.transfer_number}</span></strong><span>{labels.date}: {date}</span></div></header><section className="transfer-note__locations"><div className="transfer-note__location"><span className="transfer-note__location-label">{labels.from}</span><strong className="transfer-note__location-name">{transfer.source_name}</strong>{transfer.source_address?<span className="transfer-note__address">{transfer.source_address}</span>:null}</div><div className="transfer-note__location"><span className="transfer-note__location-label">{labels.to}</span><strong className="transfer-note__location-name">{transfer.destination_name}</strong>{transfer.destination_address?<span className="transfer-note__address">{transfer.destination_address}</span>:null}</div></section><div className="transfer-note__table-wrap"><table className="transfer-note__table"><thead><tr>{labels.headings.map(heading=><th key={heading}>{heading}</th>)}</tr></thead><tbody>{items.map(item=><tr key={item.id??item.line_number}>{[item.line_number,item.category_name,item.article_number,item.producer,item.size,item.weight_grams,item.price_per_gram,item.price,item.barcode].map((value,index)=><td key={index}>{index>=5&&index<=7&&typeof value==="number"?number.format(value):display(value)}</td>)}</tr>)}</tbody></table></div><section className="transfer-note__summary"><div><span>{labels.itemCount}</span><strong>{transfer.item_count}</strong></div><div><span>{labels.totalWeight}</span><strong>{number.format(transfer.total_weight)} g</strong></div><div><span>{labels.totalValue}</span><strong>{money.format(transfer.total_value)}</strong></div></section><p className="transfer-note__performed"><strong>{labels.performedBy}:</strong> {transfer.performed_by_name}</p><section className="transfer-note__signatures"><div className="transfer-note__signature">{labels.sender}</div><div className="transfer-note__signature">{labels.receiver}</div></section></article></>;
}
