import { describe, expect, it, vi } from "vitest";
vi.mock("server-only",()=>({}));
import { transferHtml, transferPdf, transferPdfFilename } from "./pdf";
import { createTranslator } from "@/lib/i18n/core";
import { transferNoteLabels } from "./labels";

const transfer={transfer_number:"TR-20260913-000123",transferred_at:"2026-09-13T12:00:00Z",source_name:"Склад",destination_name:"Камінь",source_address:"вул. Центральна, 1",destination_address:null,performed_by_name:"admin",item_count:1,total_weight:2.5,total_value:38320};
const items=[{line_number:1,category_name:"Каблучка",article_number:"А-1",producer:"Україна",size:"17",weight_grams:2.5,price_per_gram:15328,price:38320,barcode:"123456"}];
const labels={title:"Накладна переміщення",number:"№ документа",date:"Дата створення",from:"Звідки",to:"Куди",itemCount:"Вироби",totalWeight:"Загальна вага",totalValue:"Загальна вартість",performedBy:"Створив",sender:"Передав",receiver:"Прийняв",headings:["№","Виріб","Артикул","Виробник","Розмір","Вага","Ціна за грам","Ціна (грн)","Штрихкод"]};

describe("transfer PDF",()=>{
  it("renders safe canonical Ukrainian HTML with print pagination rules",async()=>{const html=await transferHtml(transfer,items,labels,"ua");expect(html).toContain('lang="uk"');expect(html).toContain("Дата створення");expect(html).toContain("Створив");expect(html).toContain("admin");expect(html).not.toContain("Створив / виконав");expect(html).not.toContain("Ціна закупки");expect(html).toContain("data:image/png;base64,");expect(html).toContain("@page{size:A4 portrait");expect(html).toContain("display:table-header-group");expect(html).toContain("page-break-inside:avoid")});
  it("shows both locations, preserves a real address, and omits the empty-address dash",async()=>{const html=await transferHtml(transfer,items,labels,"ua"),locations=html.slice(html.indexOf('class="transfer-note__locations"'),html.indexOf('class="transfer-note__table-wrap"'));expect(locations).toContain("Склад");expect(locations).toContain("Камінь");expect(locations).toContain("вул. Центральна, 1");expect(locations).not.toContain("—")});
  it.each(["en","ua"] as const)("uses localized numeric-only price cells and currency-bearing %s headers",async locale=>{const html=await transferHtml(transfer,[{...items[0],price_per_gram:1200,price:6000}],transferNoteLabels(createTranslator(locale)),locale),normalized=html.replace(/[\u00a0\u202f]/g," "),priceCells=[...normalized.matchAll(/<td class="transfer-note__cell--price(?:-per-gram)?">([^<]+)<\/td>/g)].map(match=>match[1]);expect(normalized).toContain(locale==="en"?"Price per Gram (UAH)":"Ціна за грам (грн)");expect(priceCells).toEqual(locale==="en"?["1,200.00","6,000.00"]:["1 200,00","6 000,00"]);expect(priceCells.join(" ")).not.toMatch(/UAH|грн/)});
  it("preserves long articles, producers, prices, and barcodes in semantic columns",async()=>{const longItem={...items[0],category_name:"Extremely long multi word product category",article_number:"ARTICLE-WITH-A-LONG-IDENTIFIER-2026",producer:"Producer With A Very Long Registered Business Name",price_per_gram:1234567.89,price:9876543.21,barcode:"012345678901234567890123456789"},html=await transferHtml({...transfer,item_count:2},[longItem,items[0]],transferNoteLabels(createTranslator("en")),"en");for(const value of[longItem.category_name,longItem.article_number,longItem.producer,longItem.barcode])expect(html).toContain(value);expect(html).toContain("transfer-note__col--category");expect(html).toContain("transfer-note__col--barcode");expect(html).toContain("transfer-note--compact-table");expect(html).not.toContain("text-overflow:ellipsis")});
  it.skipIf(process.env.CI)("creates a valid A4 PDF from the canonical HTML in local headless Chromium",async()=>{const pdf=await transferPdf(transfer,items,labels,"ua");expect(Buffer.from(pdf.subarray(0,5)).toString()).toBe("%PDF-");expect(pdf.byteLength).toBeGreaterThan(10_000)});
  it("uses the complete transfer number in a meaningful filename",()=>expect(transferPdfFilename(transfer.transfer_number)).toBe("transfer-TR-20260913-000123.pdf"));
});
