import { describe, expect, it, vi } from "vitest";
vi.mock("server-only",()=>({}));
import { transferHtml, transferPdf, transferPdfFilename } from "./pdf";
import { createTranslator } from "@/lib/i18n/core";
import { transferNoteLabels } from "./labels";

const transfer={transfer_number:"TR-20260913-000123",transferred_at:"2026-09-13T12:00:00Z",source_name:"Склад",destination_name:"Камінь",source_address:"вул. Центральна, 1",destination_address:null,performed_by_name:"admin",item_count:1,total_weight:2.5,total_value:38320};
const items=[{line_number:1,category_name:"Каблучка",article_number:"А-1",producer:"Україна",size:"17",weight_grams:2.5,price_per_gram:15328,price:38320,barcode:"123456"}];
const labels={title:"Накладна переміщення",number:"№ документа",date:"Дата створення",from:"Звідки",to:"Куди",itemCount:"Вироби",totalWeight:"Загальна вага",totalValue:"Загальна вартість",performedBy:"Створив",sender:"Передав",receiver:"Прийняв",headings:["№","Виріб","Артикул","Виробник","Розмір","Вага","Ціна/г, грн","Ціна, грн","Штрихкод"]};

describe("transfer PDF",()=>{
  it("renders safe canonical Ukrainian HTML with print pagination rules",async()=>{const html=await transferHtml(transfer,items,labels,"ua");expect(html).toContain('lang="uk"');expect(html).toContain("Дата створення");expect(html).toContain("Створив");expect(html).toContain("admin");expect(html).not.toContain("Створив / виконав");expect(html).not.toContain("Ціна закупки");expect(html).toContain("data:image/png;base64,");expect(html).toContain("@page{size:A4 portrait");expect(html).toContain("display:table-header-group");expect(html).toContain("page-break-inside:avoid")});
  it("shows both locations, preserves a real address, and omits the empty-address dash",async()=>{const html=await transferHtml(transfer,items,labels,"ua"),locations=html.slice(html.indexOf('class="transfer-note__locations"'),html.indexOf('class="transfer-note__table-wrap"'));expect(locations).toContain("Склад");expect(locations).toContain("Камінь");expect(locations).toContain("вул. Центральна, 1");expect(locations).not.toContain("—")});
  it.each(["en","ua"] as const)("uses localized numeric-only boundary prices and concise %s headers",async locale=>{const html=await transferHtml(transfer,[{...items[0],price_per_gram:24390,price:295607}],transferNoteLabels(createTranslator(locale)),locale),normalized=html.replace(/[\u00a0\u202f]/g," "),priceCells=[...normalized.matchAll(/<td class="transfer-note__cell--price(?:-per-gram)?">([^<]+)<\/td>/g)].map(match=>match[1]);if(locale==="en")expect(normalized).toContain('transfer-note__heading-main\">Price per Gram</span><span class="transfer-note__heading-unit\">(UAH)');else{expect(normalized).toContain('transfer-note__heading-main\">Ціна/г, грн</span>');expect(normalized).toContain('transfer-note__heading-main\">Ціна, грн</span>')}expect(priceCells).toEqual(locale==="en"?["24,390.00","295,607.00"]:["24 390,00","295 607,00"]);expect(priceCells.join(" ")).not.toMatch(/UAH|грн/)});
  it("locks the Ukrainian transfer profile to realistic maximum field envelopes",async()=>{const boundary={...items[0],category_name:"Перстень діаманти (0,05ct)",article_number:"shmfpD600040|R55",producer:"Золотий Соверен",size:"17,5-18,5",weight_grams:12.12,price_per_gram:24390,price:295607,barcode:"12345678901234567890"},html=await transferHtml({...transfer,item_count:3},[boundary,items[0],{...items[0],line_number:3}],transferNoteLabels(createTranslator("ua")),"ua"),normalized=html.replace(/[\u00a0\u202f]/g," ");for(const value of[boundary.category_name,boundary.article_number,boundary.producer,boundary.size,boundary.barcode,"24 390,00","295 607,00"])expect(normalized).toContain(value);for(const rule of['article class="transfer-note transfer-note--ua-table"',"transfer-note--ua-table .transfer-note__col--category{width:17%}","transfer-note--ua-table .transfer-note__col--article{width:16%}","transfer-note--ua-table .transfer-note__col--price-per-gram{width:10.5%}","transfer-note--ua-table .transfer-note__col--price{width:10.5%}","transfer-note--ua-table .transfer-note__col--barcode{width:16%}","td.transfer-note__cell--article{white-space:nowrap"])expect(html).toContain(rule);expect(html).not.toContain("text-overflow:ellipsis");expect(html).not.toContain("word-break:break-all")});
  it.skipIf(process.env.CI)("creates a valid A4 PDF from the canonical HTML in local headless Chromium",async()=>{const pdf=await transferPdf(transfer,items,labels,"ua");expect(Buffer.from(pdf.subarray(0,5)).toString()).toBe("%PDF-");expect(pdf.byteLength).toBeGreaterThan(10_000)});
  it("uses the complete transfer number in a meaningful filename",()=>expect(transferPdfFilename(transfer.transfer_number)).toBe("transfer-TR-20260913-000123.pdf"));
});
