-- Historical dashboard metrics must use immutable sale-line snapshots.
create or replace function public.get_dashboard_report(p_period text default 'THIS_MONTH',p_shop_id uuid default null)
returns jsonb language plpgsql stable security definer set search_path='' set row_security=off as $$
declare e public.employees%rowtype;sid uuid;period text:=upper(coalesce(p_period,''));today date:=(statement_timestamp() at time zone 'Europe/Kyiv')::date;started timestamptz;ended timestamptz;k jsonb;inv jsonb;statuses jsonb;recent jsonb;trend jsonb;categories jsonb;shops_report jsonb;
begin
  select x.* into e from public.employees x where x.auth_user_id=(select auth.uid()) and x.is_active limit 1;
  if not found or e.role not in ('owner','salesperson') then raise exception using errcode='42501',message='An active employee account is required.'; end if;
  if e.role='owner' then sid:=p_shop_id;if sid is not null and not exists(select 1 from public.shops where id=sid and is_active) then raise exception using errcode='42501',message='You cannot report on this shop.';end if;
  else if e.shop_id is null or not exists(select 1 from public.shops where id=e.shop_id and is_active) then raise exception using errcode='42501',message='An active assigned shop is required.';end if;if p_shop_id is not null and p_shop_id<>e.shop_id then raise exception using errcode='42501',message='You cannot report on another shop.';end if;sid:=e.shop_id;end if;
  if period='TODAY' then started:=today::timestamp at time zone 'Europe/Kyiv';elsif period='LAST_7_DAYS' then started:=(today-6)::timestamp at time zone 'Europe/Kyiv';elsif period='THIS_MONTH' then started:=date_trunc('month',today::timestamp) at time zone 'Europe/Kyiv';elsif period='LAST_30_DAYS' then started:=(today-29)::timestamp at time zone 'Europe/Kyiv';else raise exception using errcode='22023',message='Select a supported reporting period.';end if;ended:=(today+1)::timestamp at time zone 'Europe/Kyiv';
  select jsonb_build_object('revenue',coalesce(sum(s.total_sale_price),0),'sales_count',count(*)::int,'items_sold',coalesce(sum(x.items),0)::int,'gold_weight_sold',coalesce(sum(x.weight),0),'average_sale',case when count(*)=0 then 0 else round(sum(s.total_sale_price)/count(*),2) end) into k from public.sales s cross join lateral(select count(*) items,coalesce(sum(si.weight_grams),0) weight from public.sale_items si where si.sale_id=s.id)x where s.sold_at>=started and s.sold_at<ended and(sid is null or s.shop_id=sid);
  if e.role='owner' then
    select jsonb_build_object('in_stock_items',count(*)::int,'in_stock_weight',coalesce(sum(i.weight_grams),0),'customer_value',coalesce(sum(p.effective_price),0),'missing_price_items',count(*)filter(where p.effective_price is null)::int) into inv from public.inventory_items i join public.shops sh on sh.id=i.shop_id and sh.is_active cross join lateral public.get_effective_inventory_price(i.id)p where i.status='IN_STOCK' and(sid is null or i.shop_id=sid);
    select jsonb_build_object('IN_STOCK',count(*)filter(where status='IN_STOCK'),'SOLD',count(*)filter(where status='SOLD'),'REMOVED',count(*)filter(where status='REMOVED')) into statuses from public.inventory_items where sid is null or shop_id=sid;
    select coalesce(jsonb_agg(jsonb_build_object('date',d.report_day,'revenue',coalesce(t.revenue,0),'sales_count',coalesce(t.sales_count,0))order by d.report_day),'[]') into trend from generate_series((started at time zone 'Europe/Kyiv')::date,(ended at time zone 'Europe/Kyiv')::date-1,interval '1 day')d(report_day) left join(select(sold_at at time zone 'Europe/Kyiv')::date report_day,sum(total_sale_price)revenue,count(*)sales_count from public.sales where sold_at>=started and sold_at<ended and(sid is null or shop_id=sid)group by 1)t on t.report_day=d.report_day;
    select coalesce(jsonb_agg(row_data order by(row_data->>'revenue')::numeric desc),'[]')into categories from(select jsonb_build_object('category',coalesce(si.category_name,'Uncategorized'),'items_sold',count(*)::int,'revenue',coalesce(sum(si.sale_price),0),'weight_sold',coalesce(sum(si.weight_grams),0))row_data from public.sale_items si join public.sales s on s.id=si.sale_id where s.sold_at>=started and s.sold_at<ended and(sid is null or s.shop_id=sid)group by coalesce(si.category_name,'Uncategorized'))q;
    if sid is null then select coalesce(jsonb_agg(row_data order by(row_data->>'revenue')::numeric desc),'[]')into shops_report from(select jsonb_build_object('shop_id',sh.id,'shop',sh.name,'revenue',coalesce(sd.revenue,0),'sales_count',coalesce(sd.sales_count,0),'items_sold',coalesce(sd.items,0),'weight_sold',coalesce(sd.weight,0),'in_stock_items',coalesce(st.items,0),'in_stock_weight',coalesce(st.weight,0),'inventory_value',coalesce(st.value,0))row_data from public.shops sh left join lateral(select sum(si.sale_price)revenue,count(distinct s.id)::int sales_count,count(si.id)::int items,coalesce(sum(si.weight_grams),0)weight from public.sales s left join public.sale_items si on si.sale_id=s.id where s.shop_id=sh.id and s.sold_at>=started and s.sold_at<ended)sd on true left join lateral(select count(*)::int items,coalesce(sum(i.weight_grams),0)weight,coalesce(sum(p.effective_price),0)value from public.inventory_items i cross join lateral public.get_effective_inventory_price(i.id)p where i.shop_id=sh.id and i.status='IN_STOCK')st on true where sh.is_active)q;end if;
  end if;
  select coalesce(jsonb_agg(jsonb_build_object('id',s.id,'sale_number',s.sale_number,'sold_at',s.sold_at,'shop',sh.name,'employee',coalesce(emp.full_name,'Staff member'),'item_count',x.items,'total_sale_price',s.total_sale_price)order by s.sold_at desc),'[]')into recent from(select * from public.sales where(sid is null or shop_id=sid)order by sold_at desc limit 10)s join public.shops sh on sh.id=s.shop_id join public.employees emp on emp.id=s.employee_id cross join lateral(select count(*)::int items from public.sale_items where sale_id=s.id)x;
  return jsonb_build_object('role',e.role,'period',period,'timezone','Europe/Kyiv','start_at',started,'end_at',ended,'shop_id',sid,'kpis',k,'inventory',inv,'status_counts',statuses,'recent_sales',recent,'sales_over_time',trend,'categories',categories,'shops',shops_report);
end $$;
revoke all on function public.get_dashboard_report(text,uuid) from public,anon;
grant execute on function public.get_dashboard_report(text,uuid) to authenticated;
comment on function public.get_dashboard_report(text,uuid) is 'Role-scoped dashboard; historical category and weight metrics use immutable sale_items snapshots.';
