-- Expose the existing nullable fineness attribute throughout imports/audit and summarize multi-item sales.
create or replace function public.record_inventory_history() returns trigger language plpgsql security definer set search_path='' set row_security=off as $$
declare v_employee uuid;v_source text;v_sale uuid;v_field text;v_old text;v_new text;
begin
 select id into v_employee from public.employees where auth_user_id=(select auth.uid()) and is_active limit 1;
 v_source:=coalesce(nullif(current_setting('gold.audit_source',true),''),case when tg_op='INSERT' then 'SYSTEM' else 'MANUAL_EDIT' end);
 begin v_sale:=nullif(current_setting('gold.audit_sale_id',true),'')::uuid;exception when invalid_text_representation then v_sale:=null;end;
 if tg_op='INSERT' then insert into public.inventory_item_history(inventory_item_id,field_name,new_value,changed_by_employee_id,source,sale_id)values(new.id,'CREATED','Inventory item created',v_employee,v_source,v_sale);return new;end if;
 for v_field,v_old,v_new in select * from(values
  ('Product Category',old.category_id::text,new.category_id::text),('Metal',old.metal,new.metal),('Fineness',old.gold_fineness,new.gold_fineness),('Producer',old.producer,new.producer),('Size',old.size,new.size),('Article',old.article_number,new.article_number),('Weight',old.weight_grams::text,new.weight_grams::text),('Price per Gram',old.price_per_gram::text,new.price_per_gram::text),('Inventory Price',old.price::text,new.price::text),('Inventory Discount',old.discount,new.discount),('Status',old.status,new.status),('Shop',old.shop_id::text,new.shop_id::text),('Barcode',old.barcode,new.barcode),('Notes',old.notes,new.notes),('Owner/base price',old.owner_price::text,new.owner_price::text),('Manual selling price',old.selling_price::text,new.selling_price::text)
 )changes(field_name,old_value,new_value)where old_value is distinct from new_value loop
  if v_field='Shop' then select name into v_old from public.shops where id=old.shop_id;select name into v_new from public.shops where id=new.shop_id;
  elsif v_field='Product Category' then select name into v_old from public.product_categories where id=old.category_id;select name into v_new from public.product_categories where id=new.category_id;end if;
  insert into public.inventory_item_history(inventory_item_id,field_name,old_value,new_value,changed_by_employee_id,source,sale_id)values(new.id,v_field,v_old,v_new,v_employee,case when v_source='MANUAL_EDIT' and v_field='Status' then 'STATUS_CHANGE' when v_source='MANUAL_EDIT' and v_field='Shop' then 'SHOP_TRANSFER' else v_source end,v_sale);
 end loop;return new;
end $$;
revoke all on function public.record_inventory_history() from public,anon,authenticated;

create or replace function public.import_inventory_items(p_items jsonb)returns integer language plpgsql security definer set search_path='' set row_security=off as $$
declare employee public.employees%rowtype;inserted_count integer;
begin
 select * into employee from public.employees where auth_user_id=(select auth.uid())and is_active limit 1;
 if not found or employee.role<>'owner' then raise exception using errcode='42501',message='Owner access required.';end if;
 if p_items is null or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)<1 or jsonb_array_length(p_items)>100 then raise exception using errcode='22023',message='Import batch must contain 1 to 100 items.';end if;
 if exists(select 1 from jsonb_to_recordset(p_items)item(shop_id uuid,status text)where item.shop_id is null or not public.can_access_shop(item.shop_id)or not exists(select 1 from public.shops shop where shop.id=item.shop_id and shop.is_active)or coalesce(item.status,'IN_STOCK')='SOLD')then raise exception using errcode='42501',message='Import contains an unauthorized shop or SOLD status.';end if;
 perform set_config('gold.audit_source','XLSX_IMPORT',true);
 insert into public.inventory_items(shop_id,barcode,article_number,category_id,metal,gold_fineness,producer,size,weight_grams,price_per_gram,discount,notes,status,created_by)
 select item.shop_id,nullif(btrim(item.barcode),''),nullif(btrim(item.article_number),''),public.resolve_product_category(item.category_name),item.metal,nullif(btrim(item.gold_fineness),''),nullif(btrim(item.producer),''),nullif(btrim(item.size),''),item.weight_grams,item.price_per_gram,nullif(btrim(item.discount),''),nullif(btrim(item.notes),''),coalesce(item.status,'IN_STOCK'),employee.id
 from jsonb_to_recordset(p_items)item(shop_id uuid,barcode text,article_number text,category_name text,metal text,gold_fineness text,producer text,size text,weight_grams numeric,price_per_gram numeric,discount text,notes text,status text);
 get diagnostics inserted_count=row_count;return inserted_count;
end $$;
revoke all on function public.import_inventory_items(jsonb)from public,anon;grant execute on function public.import_inventory_items(jsonb)to authenticated;

create or replace function public.get_dashboard_report(p_period text default 'THIS_MONTH',p_shop_id uuid default null)
returns jsonb language plpgsql stable security definer set search_path='' set row_security=off as $$
declare e public.employees%rowtype;sid uuid;period text:=upper(coalesce(p_period,''));today date:=(statement_timestamp()at time zone 'Europe/Kyiv')::date;started timestamptz;ended timestamptz;k jsonb;inv jsonb;statuses jsonb;recent jsonb;trend jsonb;categories jsonb;shops_report jsonb;
begin
 select x.* into e from public.employees x where x.auth_user_id=(select auth.uid())and x.is_active limit 1;
 if not found or e.role not in('owner','salesperson')then raise exception using errcode='42501',message='An active employee account is required.';end if;
 if e.role='owner' then sid:=p_shop_id;if sid is not null and not exists(select 1 from public.shops where id=sid and is_active)then raise exception using errcode='42501',message='You cannot report on this shop.';end if;else if e.shop_id is null or not exists(select 1 from public.shops where id=e.shop_id and is_active)then raise exception using errcode='42501',message='An active assigned shop is required.';end if;if p_shop_id is not null and p_shop_id<>e.shop_id then raise exception using errcode='42501',message='You cannot report on another shop.';end if;sid:=e.shop_id;end if;
 if period='TODAY' then started:=today::timestamp at time zone 'Europe/Kyiv';elsif period='LAST_7_DAYS' then started:=(today-6)::timestamp at time zone 'Europe/Kyiv';elsif period='THIS_MONTH' then started:=date_trunc('month',today::timestamp)at time zone 'Europe/Kyiv';elsif period='LAST_30_DAYS' then started:=(today-29)::timestamp at time zone 'Europe/Kyiv';else raise exception using errcode='22023',message='Select a supported reporting period.';end if;ended:=(today+1)::timestamp at time zone 'Europe/Kyiv';
 select jsonb_build_object('revenue',coalesce(sum(s.total_sale_price),0),'sales_count',count(*)::int,'items_sold',coalesce(sum(x.items),0)::int,'gold_weight_sold',coalesce(sum(x.weight),0),'average_sale',case when count(*)=0 then 0 else round(sum(s.total_sale_price)/count(*),2)end)into k from public.sales s cross join lateral(select count(*)items,coalesce(sum(si.weight_grams),0)weight from public.sale_items si where si.sale_id=s.id)x where s.sold_at>=started and s.sold_at<ended and(sid is null or s.shop_id=sid);
 if e.role='owner' then
  select jsonb_build_object('in_stock_items',count(*)::int,'in_stock_weight',coalesce(sum(i.weight_grams),0),'customer_value',coalesce(sum(p.effective_price),0),'missing_price_items',count(*)filter(where p.effective_price is null)::int)into inv from public.inventory_items i join public.shops sh on sh.id=i.shop_id and sh.is_active cross join lateral public.get_effective_inventory_price(i.id)p where i.status='IN_STOCK' and(sid is null or i.shop_id=sid);
  select jsonb_build_object('IN_STOCK',count(*)filter(where status='IN_STOCK'),'SOLD',count(*)filter(where status='SOLD'),'REMOVED',count(*)filter(where status='REMOVED'))into statuses from public.inventory_items where sid is null or shop_id=sid;
  select coalesce(jsonb_agg(jsonb_build_object('date',d.report_day,'revenue',coalesce(t.revenue,0),'sales_count',coalesce(t.sales_count,0))order by d.report_day),'[]')into trend from generate_series((started at time zone 'Europe/Kyiv')::date,(ended at time zone 'Europe/Kyiv')::date-1,interval '1 day')d(report_day)left join(select(sold_at at time zone 'Europe/Kyiv')::date report_day,sum(total_sale_price)revenue,count(*)sales_count from public.sales where sold_at>=started and sold_at<ended and(sid is null or shop_id=sid)group by 1)t on t.report_day=d.report_day;
  select coalesce(jsonb_agg(row_data order by(row_data->>'revenue')::numeric desc),'[]')into categories from(select jsonb_build_object('category',coalesce(si.category_name,'Uncategorized'),'items_sold',count(*)::int,'revenue',coalesce(sum(si.sale_price),0),'weight_sold',coalesce(sum(si.weight_grams),0))row_data from public.sale_items si join public.sales s on s.id=si.sale_id where s.sold_at>=started and s.sold_at<ended and(sid is null or s.shop_id=sid)group by coalesce(si.category_name,'Uncategorized'))q;
  if sid is null then select coalesce(jsonb_agg(row_data order by(row_data->>'revenue')::numeric desc),'[]')into shops_report from(select jsonb_build_object('shop_id',sh.id,'shop',sh.name,'revenue',coalesce(sd.revenue,0),'sales_count',coalesce(sd.sales_count,0),'items_sold',coalesce(sd.items,0),'weight_sold',coalesce(sd.weight,0),'in_stock_items',coalesce(st.items,0),'in_stock_weight',coalesce(st.weight,0),'inventory_value',coalesce(st.value,0))row_data from public.shops sh left join lateral(select sum(si.sale_price)revenue,count(distinct s.id)::int sales_count,count(si.id)::int items,coalesce(sum(si.weight_grams),0)weight from public.sales s left join public.sale_items si on si.sale_id=s.id where s.shop_id=sh.id and s.sold_at>=started and s.sold_at<ended)sd on true left join lateral(select count(*)::int items,coalesce(sum(i.weight_grams),0)weight,coalesce(sum(p.effective_price),0)value from public.inventory_items i cross join lateral public.get_effective_inventory_price(i.id)p where i.shop_id=sh.id and i.status='IN_STOCK')st on true where sh.is_active)q;end if;
 end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',s.id,'sale_number',s.sale_number,'sold_at',s.sold_at,'shop',coalesce(sh.name,s.shop_name,'Deleted shop'),'employee',coalesce(emp.full_name,s.employee_name,s.employee_username,'Deleted account'),'item_count',x.items,'category_summary',x.category_summary,'total_sale_price',s.total_sale_price)order by s.sold_at desc),'[]')into recent from(select * from public.sales where(sid is null or shop_id=sid)order by sold_at desc limit 10)s left join public.shops sh on sh.id=s.shop_id left join public.employees emp on emp.id=s.employee_id cross join lateral(select sum(c.category_count)::int items,string_agg(case when c.category_count=1 then c.category else c.category||' × '||c.category_count end,', ' order by c.category)category_summary from(select coalesce(si.category_name,'Uncategorized')category,count(*)::int category_count from public.sale_items si where si.sale_id=s.id group by coalesce(si.category_name,'Uncategorized'))c)x;
 return jsonb_build_object('role',e.role,'period',period,'timezone','Europe/Kyiv','start_at',started,'end_at',ended,'shop_id',sid,'kpis',k,'inventory',inv,'status_counts',statuses,'recent_sales',recent,'sales_over_time',trend,'categories',categories,'shops',shops_report);
end $$;
revoke all on function public.get_dashboard_report(text,uuid)from public,anon;grant execute on function public.get_dashboard_report(text,uuid)to authenticated;
comment on function public.get_dashboard_report(text,uuid)is 'Role-scoped dashboard with one recent-sales row per sale and immutable category summaries.';
