create or replace function public.bulk_move_inventory_items_with_transfer(p_inventory_item_ids uuid[],p_shop_id uuid)
returns uuid language plpgsql security definer set search_path='' set row_security=off as $$
declare v_actor public.employees%rowtype;v_requested int;v_source_count int;v_source_id uuid;v_source public.shops%rowtype;v_dest public.shops%rowtype;v_transfer uuid;
begin v_actor:=public.require_owner_employee();v_requested:=coalesce(array_length(p_inventory_item_ids,1),0);
if v_requested<1 or v_requested>50 or v_requested<>(select count(distinct x)from unnest(p_inventory_item_ids)x)then raise exception using errcode='22023',message='Select 1 to 50 unique products.';end if;
if p_shop_id is null then raise exception using errcode='22023',message='Select an active destination location.';end if;select*into v_dest from public.shops where id=p_shop_id and is_active;if not found then raise exception using errcode='22023',message='Select an active destination location.';end if;
perform i.id from public.inventory_items i where i.id=any(p_inventory_item_ids)order by i.id for update;if(select count(*)from public.inventory_items where id=any(p_inventory_item_ids))<>v_requested then raise exception using errcode='22023',message='A selected product no longer exists.';end if;
if exists(select 1 from public.inventory_items where id=any(p_inventory_item_ids)and status not in('IN_STOCK','REMOVED'))then raise exception using errcode='22023',message='SOLD products cannot be moved.';end if;
select count(distinct shop_id),(array_agg(distinct shop_id))[1]into v_source_count,v_source_id from public.inventory_items where id=any(p_inventory_item_ids);if v_source_count<>1 or v_source_id is null then raise exception using errcode='22023',message='Selected products must have one assigned source location.';end if;select*into v_source from public.shops where id=v_source_id;if v_source.id=v_dest.id then raise exception using errcode='22023',message='Source and destination must differ.';end if;
insert into public.transfers(transfer_number,source_location_id,destination_location_id,source_name,destination_name,source_address,destination_address,performed_by_employee_id,performed_by_name,item_count,total_weight,total_value)select'TR-'||to_char(clock_timestamp(),'YYYYMMDD')||'-'||lpad(nextval('public.transfer_number_seq')::text,6,'0'),v_source.id,v_dest.id,v_source.name,v_dest.name,v_source.address,v_dest.address,v_actor.id,coalesce(v_actor.full_name,v_actor.username,'Owner'),count(*),coalesce(sum(weight_grams),0),coalesce(sum(price),0)from public.inventory_items where id=any(p_inventory_item_ids)returning id into v_transfer;
insert into public.transfer_items(transfer_id,line_number,inventory_item_id,category_name,producer,fineness,size,weight_grams,price_per_gram,price,article_number,barcode)select v_transfer,row_number()over(order by i.id),i.id,c.name,i.producer,i.gold_fineness,i.size,i.weight_grams,i.price_per_gram,i.price,i.article_number,i.barcode from public.inventory_items i left join public.product_categories c on c.id=i.category_id where i.id=any(p_inventory_item_ids);
perform set_config('gold.audit_source','SHOP_TRANSFER',true);update public.inventory_items set shop_id=p_shop_id where id=any(p_inventory_item_ids);return v_transfer;end $$;
