"use server";
import {revalidatePath} from "next/cache"; import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server"; import {createAdminClient} from "@/lib/supabase/admin"; import {requireOwner} from "./queries"; import {ADMIN_ROLES,friendlyAdminError,normalizeShopCode,validEmail} from "./validation"; import type {EmployeeRole} from "@/lib/database.types";
export type AdminState={error:string;success?:string};
const value=(form:FormData,name:string)=>String(form.get(name)??"").trim();
export async function createShop(_state:AdminState,form:FormData):Promise<AdminState>{await requireOwner();const name=value(form,"name"),code=normalizeShopCode(value(form,"code"));if(!name||name.length>200||!code||code.length>40)return{error:"Enter a valid shop name and code."};const db=await createClient();const{error}=await db.rpc("admin_create_shop",{p_name:name,p_code:code});if(error)return{error:error.code==="23505"?"Shop code already exists.":"Unable to create shop."};revalidatePath("/admin");redirect("/admin/shops");}
export async function updateShop(id:string,_state:AdminState,form:FormData):Promise<AdminState>{await requireOwner();const name=value(form,"name"),code=normalizeShopCode(value(form,"code"));const db=await createClient();const{error}=await db.rpc("admin_update_shop",{p_shop_id:id,p_name:name,p_code:code});if(error)return{error:error.code==="23505"?"Shop code already exists.":"Unable to update shop."};revalidatePath("/admin");redirect("/admin/shops");}
export async function setShopActive(id:string,active:boolean){await requireOwner();const db=await createClient();const{error}=await db.rpc("admin_set_shop_active",{p_shop_id:id,p_active:active});if(error)redirect(`/admin/shops?error=${encodeURIComponent(friendlyAdminError(error.message))}`);revalidatePath("/admin");redirect("/admin/shops");}
export async function updateEmployee(id:string,_state:AdminState,form:FormData):Promise<AdminState>{await requireOwner();const role=value(form,"role") as EmployeeRole,shop=value(form,"shop_id")||null,active=form.get("is_active")==="on";if(!ADMIN_ROLES.includes(role))return{error:"Select a valid role."};const db=await createClient();const{error}=await db.rpc("admin_update_employee",{p_employee_id:id,p_full_name:value(form,"full_name"),p_role:role,p_shop_id:shop,p_active:active});if(error)return{error:friendlyAdminError(error.message)};revalidatePath("/admin");redirect("/admin/employees");}
async function findAuthUser(email:string){const admin=createAdminClient();for(let page=1;page<=10;page++){const{data,error}=await admin.auth.admin.listUsers({page,perPage:1000});if(error)throw error;const found=data.users.find(user=>user.email?.toLowerCase()===email);if(found)return found;if(data.users.length<1000)break;}return null;}
export async function inviteEmployee(_state:AdminState,form:FormData):Promise<AdminState>{await requireOwner();const email=value(form,"email").toLowerCase(),fullName=value(form,"full_name"),role:EmployeeRole="salesperson",shop=value(form,"shop_id")||null;if(!validEmail(email)||!fullName)return{error:"Enter a valid email, name, and shop."};let admin;try{admin=createAdminClient();}catch{return{error:"Employee invitation is not configured on the server."};}const db=await createClient();const{data:prepared,error:prepareError}=await db.rpc("admin_prepare_employee_invite",{p_email:email,p_full_name:fullName,p_role:role,p_shop_id:shop});if(prepareError)return{error:friendlyAdminError(prepareError.message)};const invitationId=(prepared as {invitation_id?:string}|null)?.invitation_id;if(!invitationId)return{error:"Unable to prepare employee invitation."};try{let user=await findAuthUser(email);if(!user){const options:Parameters<typeof admin.auth.admin.inviteUserByEmail>[1]={data:{full_name:fullName}};const appUrl=process.env.NEXT_PUBLIC_APP_URL;if(appUrl)options.redirectTo=`${appUrl.replace(/\/$/,"")}/login`;const result=await admin.auth.admin.inviteUserByEmail(email,options);if(result.error||!result.data.user)throw result.error??new Error("Invite did not return a user.");user=result.data.user;}const{error}=await db.rpc("admin_finalize_employee_invite",{p_invitation_id:invitationId,p_auth_user_id:user.id});if(error)throw error;}catch{return{error:"The invitation could not be completed. It is safe to retry with the same email."};}revalidatePath("/admin");return{error:"",success:`Invitation sent to ${email}.`};}
